import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ShieldCheck, Sparkles } from 'lucide-react'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Badge } from '@/components/ui/Badge'
import { SectionLabel } from '@/components/ui/SectionLabel'
import { resolveAiRunConfig } from '@/stores/settingsStore'
import { getProviderDescriptor } from '@/services/ai/registry'
import { explainMatch, type ExplainMatchResult } from '@/services/ai/tasks/explainMatch'
import type { JobOpportunity } from '@/types/job'
import type { MasterResume } from '@/types/resume'
import type { JobAnalysis } from '@/types/analysis'

interface RecruiterReadProps {
  job: JobOpportunity
  resume: MasterResume
  analysis: JobAnalysis
}

export function RecruiterRead({ job, resume, analysis }: RecruiterReadProps) {
  const config = useMemo(() => resolveAiRunConfig(), [])

  const [result, setResult] = useState<ExplainMatchResult | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const run = async () => {
    if (!config) return
    setLoading(true)
    setError(null)
    try {
      setResult(await explainMatch({ job, resume, analysis }, config))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed.')
    } finally {
      setLoading(false)
    }
  }

  if (!config) {
    return (
      <Card className="text-center py-12">
        <Sparkles size={28} className="text-edge-2 mx-auto mb-4" aria-hidden />
        <h3 className="text-white font-medium mb-2">Connect an AI provider</h3>
        <p className="text-sm text-muted max-w-md mx-auto mb-6 leading-relaxed">
          The deterministic match report above is complete on its own. Add an AI provider to turn it
          into a recruiter's honest read of your fit for this role — verdict, angles to emphasize,
          and how to handle the gaps.
        </p>
        <Link to="/settings">
          <Button variant="subtle">Configure in Settings</Button>
        </Link>
      </Card>
    )
  }

  const providerLabel = getProviderDescriptor(config.providerId)?.label ?? config.providerId

  return (
    <div className="space-y-6">
      <Card>
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <SectionLabel>Recruiter Read</SectionLabel>
            <p className="text-xs text-faint mt-1">
              AI judgment layered on the deterministic match — never a new source of truth.
            </p>
          </div>
          <Button onClick={run} disabled={loading}>
            <Sparkles size={14} aria-hidden />
            {loading ? 'Thinking…' : result ? 'Regenerate' : 'Generate'}
          </Button>
        </div>

        {error && (
          <p className="text-sm text-red-400 mb-4" role="alert">
            {error}
          </p>
        )}

        {!result && !error && (
          <p className="text-sm text-muted leading-relaxed">
            Runs <strong className="text-ink-3">{providerLabel}</strong> ({config.model}) over your
            match facts only. It cannot see skills you don't have.
          </p>
        )}

        {result && (
          <>
            <GroundingBanner result={result} />
            <p className="text-ink-2 text-sm leading-relaxed whitespace-pre-wrap mt-4">{result.text}</p>
            <p className="text-xs text-faint mt-6 pt-4 border-t border-edge">
              Generated by {providerLabel} · {result.model}
            </p>
          </>
        )}
      </Card>
    </div>
  )
}

function GroundingBanner({ result }: { result: ExplainMatchResult }) {
  if (result.grounding.ok) {
    return (
      <div className="flex items-center gap-2 text-xs text-emerald-400">
        <ShieldCheck size={14} aria-hidden />
        Grounded — every skill mentioned traces back to your Master Resume or this job.
      </div>
    )
  }

  return (
    <div className="flex items-start gap-2 rounded-lg border border-red-800/50 bg-red-900/20 p-3">
      <AlertTriangle size={16} className="text-red-300 shrink-0 mt-0.5" aria-hidden />
      <div className="text-xs text-red-200 leading-relaxed">
        <strong>Unverified mentions:</strong>{' '}
        {result.grounding.unverifiedSkills.map((skill, i) => (
          <span key={skill}>
            {i > 0 && ', '}
            <Badge tone="red" className="mx-0.5">
              {skill}
            </Badge>
          </span>
        ))}
        <div className="mt-1.5 text-red-300/80">
          These appear in neither your Master Resume nor this job description. The AI may have
          introduced them — treat as unverified and do not put them on a resume.
        </div>
      </div>
    </div>
  )
}
