// GENERATED by scripts/bundle-worker.mjs — DO NOT EDIT. Edit worker.ts and run `yarn build:functions`.

// supabase/functions/discovery-worker/worker.ts
import { createClient } from "jsr:@supabase/supabase-js@2";

// supabase/functions/_shared/cors.ts
function allowlist() {
  const raw = Deno.env.get("ALLOWED_ORIGINS") ?? Deno.env.get("APP_URL") ?? "";
  return raw.split(",").map((value) => value.trim().replace(/\/+$/, "")).filter(Boolean);
}
function corsHeaders(req) {
  const allowed = allowlist();
  const origin = (req.headers.get("Origin") ?? "").replace(/\/+$/, "");
  const allowOrigin = allowed.length === 0 ? "*" : allowed.includes(origin) ? origin : allowed[0];
  return {
    "Access-Control-Allow-Origin": allowOrigin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, content-type",
    Vary: "Origin"
  };
}

// src/utils/id.ts
function createId() {
  return crypto.randomUUID();
}

// src/utils/dates.ts
function nowIso() {
  return (/* @__PURE__ */ new Date()).toISOString();
}
var DAY_MS = 24 * 60 * 60 * 1e3;

// src/services/ai/tasks/extractJobsCore.ts
var MAX_CANDIDATES = 50;
var MAX_DESCRIPTION_CHARS = 8e3;
var EXTRACT_SYSTEM_PROMPT = [
  "You are a data-extraction engine. You will receive a report about job openings.",
  "Extract every distinct job opening into a JSON array. Output ONLY the JSON array \u2014 no prose, no markdown, no code fences.",
  "",
  "Each element:",
  "{",
  '  "company": string,            // employer name, required',
  '  "role": string,               // job title, required',
  '  "description": string,        // everything the report says about this job: requirements, stack,',
  "                                // responsibilities. Quote or faithfully condense the report.",
  "                                // NEVER add information the report does not contain.",
  '  "url": string | null,         // direct posting/application link ONLY if present verbatim in the report.',
  "                                // Never construct or guess a URL.",
  '  "location": string | null,',
  '  "salaryRange": string | null, // only if the report states it',
  '  "workMode": "remote" | "hybrid" | "onsite" | "unknown"',
  "}",
  "",
  "If the report contains no job openings, output []."
].join("\n");
function parseJobsJson(text) {
  const start = text.indexOf("[");
  const end = text.lastIndexOf("]");
  if (start === -1 || end === -1 || end < start) {
    throw new Error("No JSON array found in the model output.");
  }
  const parsed = JSON.parse(text.slice(start, end + 1));
  if (!Array.isArray(parsed)) {
    throw new Error("Model output is not a JSON array.");
  }
  return parsed;
}
function coerceWorkMode(value) {
  if (typeof value !== "string") return "unknown";
  const lower = value.toLowerCase().trim();
  if (lower === "remote" || lower === "hybrid" || lower === "onsite" || lower === "unknown") return lower;
  if (lower.includes("remote")) return "remote";
  if (lower.includes("hybrid")) return "hybrid";
  if (lower.includes("onsite") || lower.includes("on-site") || lower.includes("office")) return "onsite";
  return "unknown";
}
function cleanOptional(value) {
  return typeof value === "string" ? value.trim() || void 0 : void 0;
}
function cleanUrl(value) {
  if (typeof value !== "string" || !value.trim()) return void 0;
  try {
    const parsed = new URL(value.trim());
    return parsed.protocol === "http:" || parsed.protocol === "https:" ? value.trim() : void 0;
  } catch {
    return void 0;
  }
}
function normalizeCandidates(raw) {
  const warnings = [];
  if (!Array.isArray(raw)) return { jobs: [], warnings: ["Model output was not an array."] };
  const jobs = [];
  let dropped = 0;
  for (const item of raw) {
    if (jobs.length >= MAX_CANDIDATES) {
      warnings.push(`Capped at ${MAX_CANDIDATES} jobs \u2014 the report contained more.`);
      break;
    }
    if (typeof item !== "object" || item === null) {
      dropped += 1;
      continue;
    }
    const record = item;
    const company = typeof record.company === "string" ? record.company.trim() : "";
    const role = typeof record.role === "string" ? record.role.trim() : "";
    if (!company || !role) {
      dropped += 1;
      continue;
    }
    const description = typeof record.description === "string" ? record.description.trim() : "";
    jobs.push({
      company,
      role,
      description: description.slice(0, MAX_DESCRIPTION_CHARS),
      url: cleanUrl(record.url),
      location: cleanOptional(record.location),
      salaryRange: cleanOptional(record.salaryRange),
      workMode: coerceWorkMode(record.workMode)
    });
  }
  if (dropped > 0) {
    warnings.push(`${dropped} entr${dropped === 1 ? "y" : "ies"} dropped: missing company or role.`);
  }
  return { jobs, warnings };
}
function toCandidates(jobs, origin, sourceNote) {
  return jobs.map((job) => ({
    ...job,
    id: createId(),
    origin,
    sourceNote,
    foundAt: nowIso()
  }));
}

// src/services/discovery/dedupe.ts
var COMPANY_SUFFIXES = /* @__PURE__ */ new Set(["inc", "incorporated", "llc", "ltd", "ltda", "gmbh", "sa", "corp", "co"]);
function normalizeText(value) {
  return value.toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu, "").replace(/[^\p{L}\p{N} ]/gu, " ").replace(/\s+/g, " ").trim();
}
function stripCompanySuffix(normalized) {
  const words = normalized.split(" ");
  while (words.length > 1 && COMPANY_SUFFIXES.has(words[words.length - 1])) {
    words.pop();
  }
  return words.join(" ");
}
function candidateKey(company, role) {
  return `${stripCompanySuffix(normalizeText(company))}::${normalizeText(role)}`;
}
function normalizeUrl(url) {
  if (!url) return void 0;
  try {
    const parsed = new URL(url);
    const path = parsed.pathname.replace(/\/+$/, "");
    return `${parsed.hostname.toLowerCase()}${path}`;
  } catch {
    return void 0;
  }
}
function dedupeCandidates(batch, ctx) {
  const boardKeys = new Set(ctx.existingJobs.map((job) => candidateKey(job.company, job.role)));
  const boardUrls = new Set(ctx.existingJobs.map((job) => normalizeUrl(job.url)).filter(Boolean));
  const queueKeys = new Set(ctx.existingCandidates.map((c) => candidateKey(c.company, c.role)));
  const queueUrls = new Set(ctx.existingCandidates.map((c) => normalizeUrl(c.url)).filter(Boolean));
  const dismissed = new Set(ctx.dismissedKeys);
  const seenKeys = /* @__PURE__ */ new Set();
  const seenUrls = /* @__PURE__ */ new Set();
  const fresh = [];
  const skipped = { asDuplicateOfBoard: 0, asDuplicateOfQueue: 0, asDismissed: 0, withinBatch: 0 };
  for (const candidate of batch) {
    const key = candidateKey(candidate.company, candidate.role);
    const url = normalizeUrl(candidate.url);
    if (seenKeys.has(key) || url && seenUrls.has(url)) {
      skipped.withinBatch += 1;
    } else if (boardKeys.has(key) || url && boardUrls.has(url)) {
      skipped.asDuplicateOfBoard += 1;
    } else if (queueKeys.has(key) || url && queueUrls.has(url)) {
      skipped.asDuplicateOfQueue += 1;
    } else if (dismissed.has(key)) {
      skipped.asDismissed += 1;
    } else {
      fresh.push(candidate);
    }
    seenKeys.add(key);
    if (url) seenUrls.add(url);
  }
  return { fresh, skipped };
}

// src/services/discovery/pipeline.ts
var MIN_SCORABLE_DESCRIPTION = 200;
function generateStrategies(profile) {
  const roles = profile.targetRoles.length > 0 ? profile.targetRoles : ["Software Engineer"];
  const seniority = profile.seniority !== "unknown" ? profile.seniority : "";
  const tech = profile.technologies.slice(0, 6).join(", ");
  const locationHint = profile.locations.join(" / ") || (profile.workModes.includes("remote") ? "Remote" : "");
  return roles.slice(0, 3).map((role, index) => ({
    id: `strategy-${index}`,
    label: role,
    query: [seniority, role, tech ? `(${tech})` : "", locationHint, ...profile.includeKeywords].filter(Boolean).join(" ").trim(),
    rationale: `Targets "${role}" using your top skills and location preferences.`
  }));
}
function candidateToEphemeralJob(candidate) {
  return {
    id: candidate.id,
    company: candidate.company,
    role: candidate.role,
    description: candidate.description,
    url: candidate.url,
    salaryRange: candidate.salaryRange,
    location: candidate.location,
    workMode: candidate.workMode,
    tags: [],
    createdAt: candidate.foundAt,
    archived: false,
    source: "discovered"
  };
}
async function runDiscovery(ctx, deps) {
  const strategies = ctx.strategies;
  const stats = { strategies: strategies.length, found: 0, fresh: 0, duplicates: 0, scored: 0, errors: 0 };
  const accumulated = [];
  for (const strategy of strategies) {
    if (accumulated.length >= ctx.maxCandidates) break;
    deps.onProgress?.({ phase: "searching", strategyLabel: strategy.label, fresh: stats.fresh });
    let postings;
    try {
      postings = await deps.source.search(strategy, deps.signal);
    } catch {
      stats.errors += 1;
      continue;
    }
    stats.found += postings.length;
    const candidates = toCandidates(postings, "agent", strategy.label);
    const { fresh, skipped } = dedupeCandidates(candidates, {
      ...ctx.dedupe,
      existingCandidates: [...ctx.dedupe.existingCandidates, ...accumulated]
    });
    stats.duplicates += skipped.asDuplicateOfBoard + skipped.asDuplicateOfQueue + skipped.asDismissed + skipped.withinBatch;
    for (const candidate of fresh) {
      if (accumulated.length >= ctx.maxCandidates) break;
      candidate.runId = ctx.runId;
      candidate.strategyId = strategy.id;
      candidate.enrichmentStatus = "none";
      if (candidate.description.trim().length >= MIN_SCORABLE_DESCRIPTION) {
        deps.onProgress?.({ phase: "scoring", strategyLabel: strategy.label, fresh: stats.fresh });
        try {
          const analysis = await deps.analyze(candidateToEphemeralJob(candidate), ctx.resume);
          candidate.matchScore = analysis.match.atsScore;
          candidate.analysis = analysis;
          stats.scored += 1;
        } catch {
          stats.errors += 1;
        }
      }
      accumulated.push(candidate);
      stats.fresh += 1;
      await deps.onCandidate(candidate);
    }
  }
  deps.onProgress?.({ phase: "done", fresh: stats.fresh });
  return stats;
}

// src/services/discovery/strategies.ts
var MAX_STRATEGIES = 6;
var SYSTEM_PROMPT = [
  "You are a job-search strategist. Given a candidate's structured search profile, produce a set of",
  "DIVERSE search strategies \u2014 different angles that together maximise coverage of relevant, currently",
  "open roles (vary the role framing, seniority, stack emphasis, industry/niche, and location).",
  "Output ONLY a JSON array \u2014 no prose, no markdown, no code fences. Each element:",
  "{",
  '  "label": string,      // short human label, e.g. "Senior React \u2014 product SaaS"',
  '  "query": string,      // a concrete web-search query for currently-open postings',
  '  "rationale": string   // one line: why this angle fits the profile',
  "}",
  `Return between 3 and ${MAX_STRATEGIES} strategies. Respect exclusions and preferences in the profile.`
].join("\n");
function buildStrategyGenPrompt(profile) {
  const lines = [
    profile.targetRoles.length ? `Target roles: ${profile.targetRoles.join(", ")}` : "",
    profile.seniority !== "unknown" ? `Seniority: ${profile.seniority}` : "",
    profile.technologies.length ? `Technologies: ${profile.technologies.join(", ")}` : "",
    profile.locations.length ? `Locations: ${profile.locations.join(", ")}` : "",
    profile.workModes.length ? `Work modes: ${profile.workModes.join(", ")}` : "",
    profile.languages.length ? `Languages: ${profile.languages.join(", ")}` : "",
    profile.salaryFloor ? `Minimum salary: ${profile.salaryFloor} ${profile.salaryCurrency ?? ""}`.trim() : "",
    profile.includeKeywords.length ? `Must include: ${profile.includeKeywords.join(", ")}` : "",
    profile.excludeKeywords.length ? `Exclude: ${profile.excludeKeywords.join(", ")}` : "",
    profile.extraInstructions ? `Notes: ${profile.extraInstructions}` : ""
  ].filter(Boolean);
  return `CANDIDATE SEARCH PROFILE:
${lines.join("\n")}`;
}
function parseStrategies(text) {
  const start = text.indexOf("[");
  const end = text.lastIndexOf("]");
  if (start === -1 || end === -1 || end < start) throw new Error("No JSON array found.");
  const parsed = JSON.parse(text.slice(start, end + 1));
  if (!Array.isArray(parsed)) throw new Error("Model output is not a JSON array.");
  const strategies = [];
  for (const item of parsed) {
    if (strategies.length >= MAX_STRATEGIES) break;
    if (typeof item !== "object" || item === null) continue;
    const record = item;
    const query = typeof record.query === "string" ? record.query.trim() : "";
    if (!query) continue;
    const label = typeof record.label === "string" && record.label.trim() ? record.label.trim() : query.slice(0, 48);
    strategies.push({
      id: `strategy-ai-${strategies.length}`,
      label,
      query,
      rationale: typeof record.rationale === "string" ? record.rationale.trim() : void 0
    });
  }
  return strategies;
}
async function generateStrategiesWithAi(profile, complete) {
  try {
    const text = await complete(`${SYSTEM_PROMPT}

${buildStrategyGenPrompt(profile)}`, {
      temperature: 0.5,
      maxTokens: 1200
    });
    const strategies = parseStrategies(text);
    return strategies.length > 0 ? strategies : generateStrategies(profile);
  } catch {
    return generateStrategies(profile);
  }
}

// src/services/ai/tasks/explainMatchCore.ts
var EXPLAIN_SYSTEM_PROMPT = [
  "You are a seasoned technical recruiter and career coach for software engineers.",
  "You are reviewing one candidate against one specific role, on the candidate\u2019s behalf.",
  "",
  "Hard rules:",
  "- Use ONLY the facts provided in the user message. Never invent skills, employers, seniority, metrics, or experience.",
  "- If the candidate is missing a required skill, say so plainly. Do not paper over gaps or flatter.",
  "- Do NOT name any technology or skill that is not in the provided lists.",
  "- Be specific and concise. No generic filler, no restating the inputs verbatim.",
  '- Write in second person to the candidate ("you").'
].join("\n");
function list(items) {
  return items.length ? items.join(", ") : "none";
}
function buildUserPrompt(input) {
  const { job, analysis } = input;
  const missingRequired = analysis.detectedStack.filter((skill) => !skill.inResume && skill.importance === "required").map((skill) => skill.canonical);
  const missingPreferred = analysis.detectedStack.filter((skill) => !skill.inResume && skill.importance === "preferred").map((skill) => skill.canonical);
  const evidence = analysis.seniorityEvidence.length ? ` (evidence: ${analysis.seniorityEvidence.join(", ")})` : "";
  return [
    `ROLE: ${job.role} at ${job.company}`,
    `DETECTED SENIORITY: ${analysis.detectedSeniority}${evidence}`,
    `ATS KEYWORD COVERAGE: ${analysis.match.atsScore}%`,
    `STRENGTHS (skills the job wants that ARE in the candidate\u2019s Master Resume): ${list(analysis.match.matched)}`,
    `MISSING MUST-HAVES (required by the job, NOT in the resume): ${list(missingRequired)}`,
    `MISSING NICE-TO-HAVES (optional in the job, NOT in the resume): ${list(missingPreferred)}`,
    "",
    "Give your honest recruiter read of this candidate for THIS role:",
    "1. Verdict \u2014 would you advance them to a first interview? Yes/no and why, in one or two sentences.",
    "2. Strongest angles to emphasize (only from the STRENGTHS above).",
    "3. The gaps most likely to cost an interview, and how to address or honestly reframe them.",
    "4. One concrete action to raise their odds for this role.",
    "Keep the whole response under 250 words."
  ].join("\n");
}

// src/constants/skillTaxonomy.ts
var SKILL_CATEGORY_LABELS = {
  frontend: "Frontend",
  backend: "Backend",
  databases: "Databases",
  cloud: "Cloud / Infra",
  ai: "AI",
  practices: "Practices"
};
var SKILL_TAXONOMY = [
  // Frontend
  { canonical: "JavaScript", aliases: ["javascript", "js", "es6"], category: "frontend" },
  { canonical: "TypeScript", aliases: ["typescript", "ts"], category: "frontend" },
  { canonical: "React", aliases: ["react", "reactjs", "react.js"], category: "frontend" },
  { canonical: "Next.js", aliases: ["next.js", "nextjs", "next"], category: "frontend" },
  { canonical: "Vue", aliases: ["vue", "vuejs", "vue.js", "nuxt"], category: "frontend" },
  { canonical: "Angular", aliases: ["angular"], category: "frontend" },
  { canonical: "Svelte", aliases: ["svelte", "sveltekit"], category: "frontend" },
  { canonical: "HTML", aliases: ["html", "html5"], category: "frontend" },
  { canonical: "CSS", aliases: ["css", "css3", "sass", "scss", "less"], category: "frontend" },
  { canonical: "Tailwind CSS", aliases: ["tailwind", "tailwindcss", "tailwind css"], category: "frontend" },
  { canonical: "Redux", aliases: ["redux"], category: "frontend" },
  { canonical: "React Native", aliases: ["react native"], category: "frontend" },
  { canonical: "Accessibility (WCAG)", aliases: ["accessibility", "wcag", "a11y"], category: "frontend" },
  { canonical: "SEO", aliases: ["seo", "search engine optimization"], category: "frontend" },
  { canonical: "Core Web Vitals", aliases: ["core web vitals", "web vitals", "lighthouse", "lcp", "cls"], category: "frontend" },
  { canonical: "Responsive Design", aliases: ["responsive design", "responsive"], category: "frontend" },
  { canonical: "Webpack", aliases: ["webpack"], category: "frontend" },
  { canonical: "Vite", aliases: ["vite"], category: "frontend" },
  // Backend
  { canonical: "Node.js", aliases: ["node.js", "nodejs", "node"], category: "backend" },
  { canonical: "Java", aliases: ["java", "jvm"], category: "backend" },
  { canonical: "Spring Boot", aliases: ["spring boot", "spring", "springboot"], category: "backend" },
  { canonical: "Kotlin", aliases: ["kotlin"], category: "backend" },
  { canonical: "Python", aliases: ["python"], category: "backend" },
  { canonical: "Django", aliases: ["django"], category: "backend" },
  { canonical: "FastAPI", aliases: ["fastapi"], category: "backend" },
  { canonical: "Go", aliases: ["golang"], category: "backend" },
  { canonical: "C#", aliases: ["c#", ".net", "dotnet"], category: "backend" },
  { canonical: "Ruby on Rails", aliases: ["ruby on rails", "rails", "ruby"], category: "backend" },
  { canonical: "PHP", aliases: ["php", "laravel"], category: "backend" },
  { canonical: "Rust", aliases: ["rust"], category: "backend" },
  { canonical: "Elixir", aliases: ["elixir", "phoenix"], category: "backend" },
  { canonical: "Express", aliases: ["express", "expressjs", "express.js"], category: "backend" },
  { canonical: "NestJS", aliases: ["nestjs", "nest.js", "nest"], category: "backend" },
  { canonical: "REST APIs", aliases: ["rest", "rest api", "rest apis", "restful"], category: "backend" },
  { canonical: "GraphQL", aliases: ["graphql", "apollo"], category: "backend" },
  { canonical: "gRPC", aliases: ["grpc"], category: "backend" },
  { canonical: "WebSockets", aliases: ["websocket", "websockets"], category: "backend" },
  { canonical: "Microservices", aliases: ["microservices", "microservice"], category: "backend" },
  { canonical: "Authentication", aliases: ["authentication", "oauth", "oauth2", "jwt", "sso"], category: "backend" },
  { canonical: "Message Queues", aliases: ["kafka", "rabbitmq", "sqs", "message queue", "pub/sub"], category: "backend" },
  // Databases
  { canonical: "PostgreSQL", aliases: ["postgresql", "postgres", "psql"], category: "databases" },
  { canonical: "MySQL", aliases: ["mysql", "mariadb"], category: "databases" },
  { canonical: "MongoDB", aliases: ["mongodb", "mongo"], category: "databases" },
  { canonical: "Redis", aliases: ["redis"], category: "databases" },
  { canonical: "SQL", aliases: ["sql"], category: "databases" },
  { canonical: "NoSQL", aliases: ["nosql", "dynamodb"], category: "databases" },
  { canonical: "Elasticsearch", aliases: ["elasticsearch", "opensearch"], category: "databases" },
  { canonical: "Supabase", aliases: ["supabase"], category: "databases" },
  { canonical: "Firebase", aliases: ["firebase", "firestore"], category: "databases" },
  { canonical: "Prisma", aliases: ["prisma"], category: "databases" },
  // Cloud / Infra
  { canonical: "AWS", aliases: ["aws", "amazon web services", "ec2", "ecs", "s3", "lambda"], category: "cloud" },
  { canonical: "Google Cloud", aliases: ["gcp", "google cloud"], category: "cloud" },
  { canonical: "Azure", aliases: ["azure"], category: "cloud" },
  { canonical: "Docker", aliases: ["docker", "containers", "containerization"], category: "cloud" },
  { canonical: "Kubernetes", aliases: ["kubernetes", "k8s"], category: "cloud" },
  { canonical: "Terraform", aliases: ["terraform", "infrastructure as code", "iac"], category: "cloud" },
  { canonical: "CI/CD", aliases: ["ci/cd", "cicd", "continuous integration", "continuous delivery", "github actions", "jenkins"], category: "cloud" },
  { canonical: "Git", aliases: ["git", "github", "gitlab"], category: "cloud" },
  { canonical: "Linux", aliases: ["linux", "unix"], category: "cloud" },
  { canonical: "Serverless", aliases: ["serverless"], category: "cloud" },
  { canonical: "Vercel", aliases: ["vercel"], category: "cloud" },
  { canonical: "Observability", aliases: ["observability", "monitoring", "datadog", "grafana", "prometheus"], category: "cloud" },
  // AI
  { canonical: "OpenAI APIs", aliases: ["openai", "gpt", "chatgpt"], category: "ai" },
  { canonical: "Claude", aliases: ["claude", "anthropic"], category: "ai" },
  { canonical: "LLMs", aliases: ["llm", "llms", "large language model", "large language models", "generative ai", "genai"], category: "ai" },
  { canonical: "Prompt Engineering", aliases: ["prompt engineering", "prompting"], category: "ai" },
  { canonical: "RAG", aliases: ["rag", "retrieval augmented generation", "embeddings", "vector database"], category: "ai" },
  { canonical: "AI Agents", aliases: ["ai agents", "agentic", "mcp"], category: "ai" },
  { canonical: "Machine Learning", aliases: ["machine learning", "ml", "pytorch", "tensorflow"], category: "ai" },
  { canonical: "AI Tooling", aliases: ["copilot", "cursor", "ai tools", "ai-assisted"], category: "ai" },
  // Practices / product / testing
  { canonical: "Testing", aliases: ["testing", "unit testing", "unit tests", "tdd"], category: "practices" },
  { canonical: "Jest", aliases: ["jest", "vitest"], category: "practices" },
  { canonical: "Cypress", aliases: ["cypress", "playwright", "e2e testing", "end-to-end testing"], category: "practices" },
  { canonical: "Agile", aliases: ["agile", "scrum", "kanban"], category: "practices" },
  { canonical: "Code Review", aliases: ["code review", "code reviews", "pull requests"], category: "practices" },
  { canonical: "System Architecture", aliases: ["architecture", "system design", "software architecture", "system architecture"], category: "practices" },
  { canonical: "Performance Optimization", aliases: ["performance", "performance optimization", "optimization"], category: "practices" },
  { canonical: "Product Engineering", aliases: ["product engineering", "product-minded", "product mindset", "product thinking"], category: "practices" },
  { canonical: "Mentorship", aliases: ["mentorship", "mentoring", "coaching"], category: "practices" },
  { canonical: "Communication", aliases: ["communication", "cross-functional", "collaboration"], category: "practices" },
  { canonical: "Ownership", aliases: ["ownership", "autonomy", "self-directed"], category: "practices" },
  { canonical: "Remote Work", aliases: ["remote", "async", "distributed team"], category: "practices" },
  { canonical: "E-commerce", aliases: ["e-commerce", "ecommerce", "headless commerce", "shopify", "vtex"], category: "practices" },
  { canonical: "SaaS", aliases: ["saas", "multi-tenant", "b2b"], category: "practices" },
  { canonical: "Security", aliases: ["security", "owasp", "appsec"], category: "practices" }
];

// src/services/analysis/extract.ts
function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function countOccurrences(text, alias) {
  const pattern = new RegExp(`(?<![a-z0-9#+.])${escapeRegex(alias)}(?![a-z0-9#+])`, "g");
  return (text.match(pattern) ?? []).length;
}
var PREFERRED_HEADINGS = ["nice to have", "nice-to-have", "bonus", "preferred", "pluses", "good to have", "desirable", "nice-to-haves"];
var REQUIRED_HEADINGS = ["requirement", "required", "must have", "must-have", "what you'll need", "what you need", "qualification", "we require", "minimum qualification", "you have"];
var INLINE_PREFERRED_MARKERS = ["a plus", "is a plus", "plus if", "nice to have", "ideally", "would be great", "good to have", "desirable", "not required", "bonus points", "a bonus"];
function segmentLines(lower) {
  const raw = lower.split(/\n|(?<=[.;])\s+/);
  const lines = [];
  let mode = "required";
  for (const chunk of raw) {
    const line = chunk.trim();
    if (!line) continue;
    if (PREFERRED_HEADINGS.some((h) => line.includes(h))) {
      mode = "preferred";
    } else if (REQUIRED_HEADINGS.some((h) => line.includes(h))) {
      mode = "required";
    }
    const lineMode = INLINE_PREFERRED_MARKERS.some((m) => line.includes(m)) ? "preferred" : mode;
    lines.push({ text: line, mode: lineMode });
  }
  return lines;
}
function extractSkills(text) {
  const lines = segmentLines(text.toLowerCase());
  const accumulator = /* @__PURE__ */ new Map();
  for (const line of lines) {
    for (const entry of SKILL_TAXONOMY) {
      for (const alias of entry.aliases) {
        const count = countOccurrences(line.text, alias);
        if (count === 0) continue;
        const rec = accumulator.get(entry) ?? { total: 0, requiredCount: 0, bestAlias: "", bestCount: 0 };
        rec.total += count;
        if (line.mode === "required") rec.requiredCount += count;
        if (count > rec.bestCount) {
          rec.bestCount = count;
          rec.bestAlias = alias;
        }
        accumulator.set(entry, rec);
      }
    }
  }
  const hits = [];
  for (const [entry, rec] of accumulator) {
    hits.push({
      entry,
      term: rec.bestAlias,
      count: rec.total,
      importance: rec.requiredCount > 0 ? "required" : "preferred"
    });
  }
  return hits.sort((a, b) => b.count - a.count);
}
var SENIORITY_TOKENS = [
  { level: "staff", pattern: /\b(staff|principal)\b/gi },
  { level: "lead", pattern: /\b(tech lead|team lead|lead engineer|engineering lead)\b/gi },
  { level: "senior", pattern: /\b(senior|sr\.?)\b/gi },
  { level: "junior", pattern: /\b(junior|jr\.?|entry[- ]level|intern(ship)?)\b/gi },
  { level: "mid", pattern: /\b(mid[- ]level|intermediate)\b/gi }
];
var YEARS_PATTERN = /(\d+)\s*(?:\+|-\d+)?\s*\+?\s*years?/gi;
function detectSeniority(text) {
  const evidence = [];
  let tokenLevel = null;
  for (const { level, pattern } of SENIORITY_TOKENS) {
    const matches = text.match(pattern);
    if (matches) {
      evidence.push(...new Set(matches.map((m) => `"${m.trim()}"`)));
      tokenLevel ??= level;
    }
  }
  let yearsLevel = null;
  for (const match of text.matchAll(YEARS_PATTERN)) {
    evidence.push(`"${match[0].trim()}"`);
    const years = Number(match[1]);
    const inferred = years >= 5 ? "senior" : years >= 3 ? "mid" : "junior";
    if (yearsLevel === null || rank(inferred) > rank(yearsLevel)) {
      yearsLevel = inferred;
    }
  }
  return {
    level: tokenLevel ?? yearsLevel ?? "unknown",
    evidence
  };
}
function rank(level) {
  const order = ["unknown", "junior", "mid", "senior", "lead", "staff"];
  return order.indexOf(level);
}

// src/services/ai/guardrails/grounding.ts
function checkGrounding(text, knownCanonical) {
  const mentioned = extractSkills(text).map((hit) => hit.entry.canonical);
  const unverified = [...new Set(mentioned.filter((canonical) => !knownCanonical.has(canonical)))];
  return {
    ok: unverified.length === 0,
    unverifiedSkills: unverified
  };
}

// src/services/analysis/match.ts
function collectResumeSkills(resume) {
  const explicitTerms = [
    ...resume.skills.map((skill) => skill.canonical),
    ...resume.projects.flatMap((project) => project.tech),
    ...resume.experience.flatMap((entry) => entry.accomplishments.flatMap((a) => a.skills)),
    ...resume.projects.flatMap((project) => project.accomplishments.flatMap((a) => a.skills))
  ].join("\n");
  const narrativeText = [
    resume.summary,
    resume.personal.location,
    resume.personal.role,
    ...resume.experience.flatMap((entry) => entry.accomplishments.map((a) => a.text)),
    ...resume.projects.flatMap((project) => [project.description, ...project.accomplishments.map((a) => a.text)])
  ].join("\n");
  const canonical = /* @__PURE__ */ new Set();
  for (const hit of extractSkills(`${explicitTerms}
${narrativeText}`)) {
    canonical.add(hit.entry.canonical);
  }
  return canonical;
}
function buildMatchReport(jdHits, resumeSkills) {
  const matchedHits = jdHits.filter((hit) => resumeSkills.has(hit.entry.canonical));
  const missingHits = jdHits.filter((hit) => !resumeSkills.has(hit.entry.canonical));
  const totalWeight = jdHits.reduce((sum, hit) => sum + weightOf(hit), 0);
  const matchedWeight = matchedHits.reduce((sum, hit) => sum + weightOf(hit), 0);
  const atsScore = totalWeight === 0 ? 0 : Math.round(matchedWeight / totalWeight * 100);
  return {
    atsScore,
    matched: matchedHits.map((hit) => hit.entry.canonical),
    missing: missingHits.map((hit) => hit.entry.canonical),
    categoryBreakdown: buildCategoryBreakdown(jdHits, resumeSkills),
    notes: buildNotes(atsScore, matchedHits, missingHits)
  };
}
function weightOf(hit) {
  return hit.importance === "required" ? hit.count * 2 : hit.count;
}
function buildCategoryBreakdown(jdHits, resumeSkills) {
  const byCategory = /* @__PURE__ */ new Map();
  for (const hit of jdHits) {
    const label = SKILL_CATEGORY_LABELS[hit.entry.category];
    const bucket = byCategory.get(label) ?? [];
    bucket.push(hit);
    byCategory.set(label, bucket);
  }
  return [...byCategory.entries()].map(([category, hits]) => {
    const matched = hits.filter((hit) => resumeSkills.has(hit.entry.canonical));
    const missing = hits.filter((hit) => !resumeSkills.has(hit.entry.canonical));
    return {
      category,
      score: Math.round(matched.length / hits.length * 5),
      matched: matched.map((hit) => hit.entry.canonical),
      missing: missing.map((hit) => hit.entry.canonical)
    };
  });
}
function buildNotes(atsScore, matched, missing) {
  const notes = [];
  if (matched.length > 0) {
    const top = matched.slice(0, 3).map((hit) => hit.entry.canonical).join(", ");
    notes.push(`Strongest overlap: ${top} \u2014 these appear most often in the job description and exist in your Master Resume.`);
  }
  const missingRequired = missing.filter((hit) => hit.importance === "required");
  const missingPreferred = missing.filter((hit) => hit.importance === "preferred");
  if (missingRequired.length > 0) {
    const top = missingRequired.slice(0, 3).map((hit) => hit.entry.canonical).join(", ");
    notes.push(`Missing must-haves: ${top} \u2014 the job frames these as requirements and your Master Resume doesn't mention them. Highest-priority gaps.`);
  }
  if (missingPreferred.length > 0) {
    const top = missingPreferred.slice(0, 3).map((hit) => hit.entry.canonical).join(", ");
    notes.push(`Missing nice-to-haves: ${top} \u2014 optional in this posting, so lower priority.`);
  }
  if (atsScore >= 75) {
    notes.push("High keyword coverage \u2014 an ATS keyword filter is unlikely to screen this profile out.");
  } else if (atsScore >= 45) {
    notes.push("Moderate keyword coverage \u2014 review the gaps above; add only skills you genuinely have to the Master Resume.");
  } else {
    notes.push("Low keyword coverage \u2014 this role may target a different stack than your Master Resume documents.");
  }
  return notes;
}

// src/services/discovery/enrich.ts
function buildRecommendation(candidate) {
  const analysis = candidate.analysis;
  if (!analysis) return "Add the full job description to get a scored recommendation.";
  const score = candidate.matchScore ?? analysis.match.atsScore;
  const missingRequired = analysis.detectedStack.filter((skill) => !skill.inResume && skill.importance === "required").map((skill) => skill.canonical);
  if (score >= 75 && missingRequired.length === 0) {
    return "Strong match \u2014 apply now and tailor your resume to lead with your matched skills.";
  }
  if (score >= 55) {
    return missingRequired.length ? `Worth a tailored application \u2014 address or honestly reframe: ${missingRequired.slice(0, 3).join(", ")}.` : "Worth a tailored application \u2014 lead with your strengths.";
  }
  return missingRequired.length ? `Stretch role \u2014 consider upskilling in ${missingRequired.slice(0, 3).join(", ")} before applying.` : "Stretch role \u2014 apply only if it strongly aligns with your goals.";
}
async function enrichCandidate(candidate, resume, complete) {
  const recommendation = buildRecommendation(candidate);
  if (!candidate.analysis) {
    return { recommendation, enrichmentStatus: "done" };
  }
  const job = candidateToEphemeralJob(candidate);
  const analysis = candidate.analysis;
  let explanation;
  try {
    const text = await complete(EXPLAIN_SYSTEM_PROMPT, buildUserPrompt({ job, resume, analysis }));
    const known = collectResumeSkills(resume);
    for (const skill of analysis.detectedStack) known.add(skill.canonical);
    if (checkGrounding(text, known).ok) explanation = text.trim();
  } catch {
  }
  return { explanation, recommendation, enrichmentStatus: "done" };
}

// src/services/discovery/signals.ts
var ACTION_WEIGHT = {
  applied: 2,
  approved: 1,
  saved: 1,
  interested: 1,
  dismissed: -1
};
function learnPreferences(signals) {
  const technologyScores = {};
  const workModeScores = {};
  const companyNet = {};
  for (const signal of signals) {
    const weight = ACTION_WEIGHT[signal.action] ?? 0;
    for (const tech of signal.features.technologies) {
      technologyScores[tech] = (technologyScores[tech] ?? 0) + weight;
    }
    if (signal.features.workMode && signal.features.workMode !== "unknown") {
      const mode = signal.features.workMode;
      workModeScores[mode] = (workModeScores[mode] ?? 0) + weight;
    }
    if (signal.features.company) {
      companyNet[signal.features.company] = (companyNet[signal.features.company] ?? 0) + weight;
    }
  }
  const dislikedCompanies = Object.entries(companyNet).filter(([, net]) => net <= -2).map(([company]) => company);
  return { technologyScores, workModeScores, dislikedCompanies };
}
var MAX_LEARNED_TECHS = 5;
function preferredTechnologies(prefs) {
  return Object.entries(prefs.technologyScores).filter(([, score]) => score > 0).sort((a, b) => b[1] - a[1]).map(([tech]) => tech).slice(0, MAX_LEARNED_TECHS);
}
function applyLearnedToProfile(profile, prefs) {
  const learnedTechs = preferredTechnologies(prefs).filter((t) => !profile.technologies.includes(t));
  const excludeCompanies = prefs.dislikedCompanies.filter((c) => !profile.excludeKeywords.includes(c));
  if (learnedTechs.length === 0 && excludeCompanies.length === 0) return profile;
  return {
    ...profile,
    technologies: [...profile.technologies, ...learnedTechs],
    excludeKeywords: [...profile.excludeKeywords, ...excludeCompanies]
  };
}

// src/services/discovery/cadence.ts
var DISCOVERY_CADENCE_HOURS = {
  free: 24,
  pro: 1
};
function isDueForRun(lastFinishedAt, tier, nowMs) {
  if (!lastFinishedAt) return true;
  const last = Date.parse(lastFinishedAt);
  if (Number.isNaN(last)) return true;
  return nowMs - last >= DISCOVERY_CADENCE_HOURS[tier] * 36e5;
}

// src/services/analysis/localHeuristicAnalyzer.ts
var LocalHeuristicAnalyzer = class {
  id = "local-heuristic-v2";
  kind = "local";
  async analyze({ job, resume }) {
    const jdText = `${job.role}
${job.description}`;
    const jdHits = extractSkills(jdText);
    const seniority = detectSeniority(jdText);
    const resumeSkills = collectResumeSkills(resume);
    const match = buildMatchReport(jdHits, resumeSkills);
    return {
      jobId: job.id,
      analyzerId: this.id,
      analyzedAt: (/* @__PURE__ */ new Date()).toISOString(),
      detectedStack: jdHits.map((hit) => ({
        term: hit.term,
        canonical: hit.entry.canonical,
        category: hit.entry.category,
        count: hit.count,
        inResume: resumeSkills.has(hit.entry.canonical),
        importance: hit.importance
      })),
      detectedSeniority: seniority.level,
      seniorityEvidence: seniority.evidence,
      atsKeywords: jdHits.map((hit) => hit.entry.canonical),
      match
    };
  }
};
function getAnalyzer() {
  return new LocalHeuristicAnalyzer();
}

// src/services/resume/projection.ts
var RESUME_FACT_TYPES = /* @__PURE__ */ new Set([
  "responsibility",
  "action",
  "achievement",
  "result",
  "business_value",
  "product_impact",
  "leadership",
  "mentoring",
  "communication",
  "stakeholder_interaction",
  "client_interaction",
  "problem_solving",
  "technical_capability"
]);
function projectKnowledgeBase(knowledgeBase) {
  const facts = knowledgeBase.facts.filter((fact) => fact.status === "confirmed");
  const skillById = new Map(knowledgeBase.skills.map((skill) => [skill.id, skill]));
  const metricById = new Map(knowledgeBase.metrics.filter((metric) => metric.status === "confirmed").map((metric) => [metric.id, metric]));
  const factsFor = (predicate) => facts.filter(predicate);
  const accomplishment = (fact) => ({
    id: fact.id,
    text: fact.statement,
    skills: fact.skillIds.map((id) => skillById.get(id)?.canonical).filter((value) => Boolean(value)),
    metric: fact.metricIds.map((id) => metricById.get(id)?.statement).find((value) => Boolean(value)),
    keywords: fact.tags
  });
  const organizationById = new Map(knowledgeBase.organizations.map((organization) => [organization.id, organization]));
  const experience = knowledgeBase.roles.map((role) => ({
    id: role.id,
    company: organizationById.get(role.organizationId)?.name ?? "",
    role: role.title,
    duration: role.period,
    location: role.location,
    accomplishments: factsFor((fact) => fact.roleIds.includes(role.id) && RESUME_FACT_TYPES.has(fact.type)).map(accomplishment)
  }));
  const projects = knowledgeBase.initiatives.map((initiative) => ({
    id: initiative.id,
    name: initiative.name,
    tech: initiative.technologySkillIds.map((id) => skillById.get(id)?.canonical).filter((value) => Boolean(value)),
    description: initiative.description ?? "",
    url: initiative.url,
    accomplishments: factsFor((fact) => fact.initiativeIds.includes(initiative.id) && RESUME_FACT_TYPES.has(fact.type)).map(accomplishment)
  }));
  const statement = (ids) => ids.map((id) => facts.find((fact) => fact.id === id)?.statement).filter((value) => Boolean(value)).join(" ");
  const stories = knowledgeBase.stories.filter((story) => story.status === "confirmed").map((story) => ({
    id: story.id,
    title: story.title,
    situation: statement(story.situationFactIds),
    task: statement(story.taskFactIds),
    action: statement(story.actionFactIds),
    result: statement(story.resultFactIds),
    skills: story.skillIds.map((id) => skillById.get(id)?.canonical).filter((value) => Boolean(value)),
    competencies: story.competencies,
    experienceId: story.roleIds[0],
    tags: story.tags
  }));
  const certifications = knowledgeBase.credentials.filter((credential) => credential.status === "confirmed" && credential.type === "certification").map((credential) => ({ id: credential.id, name: credential.name, issuer: credential.issuer ?? "", issuedAt: credential.issuedAt, expiresAt: credential.expiresAt, credentialId: credential.credentialId, url: credential.url }));
  const education = knowledgeBase.credentials.filter((credential) => credential.status === "confirmed" && credential.type === "education").map((credential) => ({ id: credential.id, institution: credential.issuer ?? "", degree: credential.name, field: credential.field ?? "", start: credential.start, end: credential.end, notes: credential.notes }));
  return {
    personal: knowledgeBase.profile.personal,
    summary: knowledgeBase.profile.summary,
    goals: knowledgeBase.profile.careerDirection,
    values: knowledgeBase.profile.values,
    experience,
    projects,
    skills: knowledgeBase.skills.map(({ evidenceFactIds: _evidenceFactIds, provenance: _provenance, ...skill }) => skill),
    stories,
    certifications,
    education,
    publications: knowledgeBase.publications.filter((publication) => publication.status === "confirmed").map(({ status: _status, provenance: _provenance, ...publication }) => publication),
    learning: knowledgeBase.learning.filter((entry) => entry.status === "confirmed").map((entry) => ({ ...entry, skills: entry.skillIds.map((id) => skillById.get(id)?.canonical).filter((value) => Boolean(value)) })),
    portfolio: knowledgeBase.portfolioAssets.filter((asset) => asset.status === "confirmed" && Boolean(asset.url)).map((asset) => ({ id: asset.id, title: asset.title, type: asset.type, url: asset.url, description: asset.description, tags: asset.tags })),
    languages: knowledgeBase.profile.languages,
    updatedAt: knowledgeBase.updatedAt
  };
}

// src/constants/seedData.ts
function createEmptyKnowledgeBase() {
  return {
    schemaVersion: 3,
    profile: {
      personal: { name: "", role: "", location: "" },
      summary: "",
      careerDirection: "",
      values: [],
      workPreferences: [],
      languages: []
    },
    organizations: [],
    roles: [],
    initiatives: [],
    skills: [],
    facts: [],
    metrics: [],
    technicalDecisions: [],
    stories: [],
    credentials: [],
    portfolioAssets: [],
    publications: [],
    learning: [],
    unclassifiedFacts: [],
    updatedAt: nowIso()
  };
}
var DEMO_SEED_ENABLED = import.meta.env?.VITE_DEMO_SEED === "true";

// supabase/functions/discovery-worker/worker.ts
var GEMINI_MODEL = Deno.env.get("GEMINI_MODEL") ?? "gemini-3.5-flash";
var GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";
var MAX_CANDIDATES_PER_RUN = 30;
var MAX_USERS_PER_TICK = 25;
var ENRICH_TOP_K = 5;
async function geminiGenerate(apiKey, prompt, grounded) {
  const res = await fetch(`${GEMINI_BASE}/models/${GEMINI_MODEL}:generateContent`, {
    method: "POST",
    headers: { "content-type": "application/json", "x-goog-api-key": apiKey },
    body: JSON.stringify({
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      tools: grounded ? [{ google_search: {} }] : void 0,
      generationConfig: { temperature: grounded ? 0.3 : 0, maxOutputTokens: 4e3 }
    })
  });
  const data = await res.json();
  if (!res.ok) throw new Error(`Gemini HTTP ${res.status}: ${JSON.stringify(data).slice(0, 200)}`);
  const text = (data?.candidates?.[0]?.content?.parts ?? []).map((p) => p?.text ?? "").join("");
  const tokens = Number(data?.usageMetadata?.totalTokenCount ?? 0);
  return { text, tokens };
}
function strategySearchPrompt(strategy) {
  return [
    "You are a job-search agent. Using live web search, find CURRENTLY OPEN job postings that match:",
    "",
    strategy.query,
    "",
    "Return a plain-text list of real, currently-open postings. For each: company, exact role title,",
    "location / work mode, salary if stated, the direct application URL (only if you actually found it),",
    "and a faithful summary of requirements/stack. Do NOT invent postings or URLs. Aim for 6\u201312 matches."
  ].join("\n");
}
var EXTRACT_PROMPT_HEAD = [
  "You are a data-extraction engine. Extract every distinct job opening from the report into a JSON",
  'array. Output ONLY the JSON array. Each element: {"company","role","description","url"|null,',
  '"location"|null,"salaryRange"|null,"workMode":"remote"|"hybrid"|"onsite"|"unknown"}. Never invent',
  "data or URLs. If none, output [].",
  "",
  "REPORT:",
  ""
].join("\n");
function createServerGeminiSource(apiKey, onTokens) {
  return {
    id: "grounded-gemini-server",
    async search(strategy) {
      const grounded = await geminiGenerate(apiKey, strategySearchPrompt(strategy), true);
      onTokens(grounded.tokens);
      const extracted = await geminiGenerate(apiKey, `${EXTRACT_PROMPT_HEAD}${grounded.text}`, false);
      onTokens(extracted.tokens);
      const { jobs } = normalizeCandidates(parseJobsJson(extracted.text));
      return jobs;
    }
  };
}
function monthlyLimitFor(tier) {
  const raw = tier === "pro" ? Deno.env.get("PRO_TIER_MONTHLY_TOKEN_LIMIT") : Deno.env.get("FREE_TIER_MONTHLY_TOKEN_LIMIT");
  const fallback = tier === "pro" ? 2e6 : 1e5;
  return raw === void 0 || raw === "" ? fallback : Number(raw);
}
async function tierOverBudget(admin, userId, tier) {
  const limit = monthlyLimitFor(tier);
  if (limit <= 0) return false;
  const monthStart = /* @__PURE__ */ new Date();
  monthStart.setUTCDate(1);
  monthStart.setUTCHours(0, 0, 0, 0);
  const { data: rows } = await admin.from("token_usage_logs").select("total_tokens").eq("user_id", userId).gte("created_at", monthStart.toISOString());
  const used = (rows ?? []).reduce((s, r) => s + (r.total_tokens ?? 0), 0);
  return used >= limit;
}
async function runForUser(admin, apiKey, userId, trigger) {
  const { data: profileRow } = await admin.from("search_profiles").select("data, scoring_snapshot").eq("user_id", userId).maybeSingle();
  const profile = profileRow?.data ?? null;
  if (!profile) return;
  const { data: sub } = await admin.from("subscriptions").select("tier").eq("user_id", userId).maybeSingle();
  const tier = sub?.tier ?? "free";
  if (await tierOverBudget(admin, userId, tier)) return;
  const { data: runRow } = await admin.from("discovery_runs").insert({ user_id: userId, trigger, status: "running", started_at: (/* @__PURE__ */ new Date()).toISOString() }).select("id").single();
  const runId = runRow?.id ?? null;
  let tokens = 0;
  const onTokens = (n) => {
    tokens += n;
  };
  try {
    const resume = profileRow?.scoring_snapshot ?? projectKnowledgeBase(createEmptyKnowledgeBase());
    const [{ data: jobRows }, { data: pendingRows }, { data: discoveryRow }] = await Promise.all([
      admin.from("jobs").select("data").eq("user_id", userId),
      admin.from("discovered_jobs").select("data").eq("user_id", userId).eq("status", "pending"),
      admin.from("discoveries").select("state").eq("user_id", userId).maybeSingle()
    ]);
    const existingJobs = (jobRows ?? []).map((r) => ({
      company: r.data.company,
      role: r.data.role,
      url: r.data.url
    }));
    const existingCandidates = (pendingRows ?? []).map((r) => r.data);
    const dismissedKeys = discoveryRow?.state?.dismissedKeys ?? [];
    const { data: signalRows } = await admin.from("discovery_signals").select("action, features").eq("user_id", userId).order("created_at", { ascending: false }).limit(500);
    const prefs = learnPreferences(signalRows ?? []);
    const learnedProfile = applyLearnedToProfile(profile, prefs);
    const strategies = await generateStrategiesWithAi(learnedProfile, async (prompt) => {
      const r = await geminiGenerate(apiKey, prompt, false);
      onTokens(r.tokens);
      return r.text;
    });
    const analyzer = getAnalyzer();
    const freshThisRun = [];
    const stats = await runDiscovery(
      { strategies, resume, dedupe: { existingJobs, existingCandidates, dismissedKeys }, maxCandidates: MAX_CANDIDATES_PER_RUN, runId: runId ?? void 0 },
      {
        source: createServerGeminiSource(apiKey, onTokens),
        analyze: (job, r) => analyzer.analyze({ job, resume: r }),
        onCandidate: async (candidate) => {
          freshThisRun.push(candidate);
          await admin.from("discovered_jobs").insert({
            id: candidate.id,
            user_id: userId,
            url: candidate.url ?? null,
            status: "pending",
            score: candidate.matchScore ?? null,
            data: candidate
          });
        }
      }
    );
    const enrichComplete = async (system, user) => {
      const r = await geminiGenerate(apiKey, `${system}

${user}`, false);
      onTokens(r.tokens);
      return r.text;
    };
    const toEnrich = freshThisRun.filter((c) => c.analysis).sort((a, b) => (b.matchScore ?? -1) - (a.matchScore ?? -1)).slice(0, ENRICH_TOP_K);
    for (const candidate of toEnrich) {
      const patch = await enrichCandidate(candidate, resume, enrichComplete);
      const patched = { ...candidate, ...patch };
      await admin.from("discovered_jobs").update({ data: patched, score: patched.matchScore ?? null }).eq("id", patched.id);
    }
    if (tokens > 0) {
      await admin.from("token_usage_logs").insert({
        user_id: userId,
        provider: "gemini",
        model: GEMINI_MODEL,
        prompt_tokens: 0,
        completion_tokens: 0,
        total_tokens: tokens
      });
    }
    await admin.from("discovery_runs").update({
      status: stats.errors > 0 && stats.fresh === 0 ? "failed" : stats.errors > 0 ? "partial" : "succeeded",
      stats,
      tokens_used: tokens,
      finished_at: (/* @__PURE__ */ new Date()).toISOString()
    }).eq("id", runId);
  } catch (err) {
    if (runId) {
      await admin.from("discovery_runs").update({
        status: "failed",
        error: String(err),
        tokens_used: tokens,
        finished_at: (/* @__PURE__ */ new Date()).toISOString()
      }).eq("id", runId);
    }
  }
}
async function selectDueUsers(admin) {
  const { data: profiles } = await admin.from("search_profiles").select("user_id").limit(500);
  const due = [];
  const nowMs = Date.now();
  for (const row of profiles ?? []) {
    if (due.length >= MAX_USERS_PER_TICK) break;
    const userId = row.user_id;
    const { data: sub } = await admin.from("subscriptions").select("tier").eq("user_id", userId).maybeSingle();
    const tier = sub?.tier ?? "free";
    const { data: lastRun } = await admin.from("discovery_runs").select("finished_at").eq("user_id", userId).eq("status", "succeeded").order("finished_at", { ascending: false }).limit(1).maybeSingle();
    if (isDueForRun(lastRun?.finished_at ?? null, tier, nowMs)) due.push(userId);
  }
  return due;
}
Deno.serve(async (req) => {
  const cors = corsHeaders(req);
  const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "content-type": "application/json" } });
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (req.method !== "POST") return json({ error: "Method not allowed." }, 405);
  const apiKey = Deno.env.get("GEMINI_API_KEY");
  if (!apiKey) return json({ error: "Server is missing GEMINI_API_KEY." }, 500);
  const url = Deno.env.get("SUPABASE_URL") ?? "";
  const admin = createClient(url, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "", { auth: { persistSession: false } });
  const cronSecret = Deno.env.get("DISCOVERY_CRON_SECRET");
  const providedSecret = req.headers.get("x-discovery-secret");
  const authHeader = req.headers.get("Authorization");
  let userIds = [];
  let trigger = "scheduled";
  if (cronSecret && providedSecret && providedSecret === cronSecret) {
    const body = await req.json().catch(() => ({}));
    userIds = Array.isArray(body.userIds) && body.userIds.length > 0 ? body.userIds.filter((id) => typeof id === "string") : await selectDueUsers(admin);
    trigger = "scheduled";
  } else if (authHeader) {
    const asUser = createClient(url, Deno.env.get("SUPABASE_ANON_KEY") ?? "", {
      global: { headers: { Authorization: authHeader } },
      auth: { persistSession: false }
    });
    const { data: { user }, error } = await asUser.auth.getUser();
    if (error || !user) return json({ error: "Invalid or expired session." }, 401);
    userIds = [user.id];
    trigger = "manual";
  } else {
    return json({ error: "Missing authorization." }, 401);
  }
  for (const userId of userIds) {
    await runForUser(admin, apiKey, userId, trigger);
  }
  return json({ ok: true, trigger, processed: userIds.length });
});
