// GENERATED by scripts/bundle-functions.mjs — DO NOT EDIT. Edit handler.ts and run `yarn build:functions`.

// supabase/functions/stripe-webhook/handler.ts
import Stripe from "npm:stripe@16";
import { createClient } from "jsr:@supabase/supabase-js@2";

// packages/email/src/errors.ts
var EmailError = class extends Error {
  /** Stable machine-readable code for branching / telemetry (never the raw message). */
  code;
  constructor(message, options) {
    super(message, { cause: options?.cause });
    this.name = "EmailError";
    this.code = options?.code ?? "EMAIL_ERROR";
  }
};
var EmailConfigError = class extends EmailError {
  constructor(message, options) {
    super(message, { code: "EMAIL_CONFIG", cause: options?.cause });
    this.name = "EmailConfigError";
  }
};
var EmailValidationError = class extends EmailError {
  constructor(message, options) {
    super(message, { code: "EMAIL_VALIDATION", cause: options?.cause });
    this.name = "EmailValidationError";
  }
};
var EmailRenderError = class extends EmailError {
  constructor(message, options) {
    super(message, { code: "EMAIL_RENDER", cause: options?.cause });
    this.name = "EmailRenderError";
  }
};
var EmailTransportError = class extends EmailError {
  /** HTTP status the provider returned, when there was one. */
  status;
  /** Whether re-sending the identical request could plausibly succeed. */
  retryable;
  /** The provider's own error identifier (e.g. Resend's `rate_limit_exceeded`). */
  providerCode;
  constructor(message, options) {
    super(message, { code: options?.code ?? "EMAIL_TRANSPORT", cause: options?.cause });
    this.name = "EmailTransportError";
    this.status = options?.status ?? null;
    this.retryable = options?.retryable ?? false;
    this.providerCode = options?.providerCode ?? null;
  }
};
var EmailRateLimitError = class extends EmailTransportError {
  /** How long the provider asked us to wait, in milliseconds, when it said. */
  retryAfterMs;
  constructor(message, options) {
    super(message, {
      code: "EMAIL_RATE_LIMIT",
      cause: options?.cause,
      status: options?.status ?? 429,
      retryable: true,
      providerCode: options?.providerCode ?? null
    });
    this.name = "EmailRateLimitError";
    this.retryAfterMs = options?.retryAfterMs ?? null;
  }
};
var EmailSuppressedError = class extends EmailError {
  recipient;
  constructor(recipient, options) {
    super(`${recipient} is suppressed and will not receive email.`, {
      code: "EMAIL_SUPPRESSED",
      cause: options?.cause
    });
    this.name = "EmailSuppressedError";
    this.recipient = recipient;
  }
};
function isEmailError(error) {
  return error instanceof EmailError;
}
function describeEmailError(error) {
  if (isEmailError(error)) return { code: error.code, message: error.message };
  if (error instanceof Error) return { code: "EMAIL_UNKNOWN", message: error.message };
  return { code: "EMAIL_UNKNOWN", message: String(error) };
}

// packages/email/src/renderer.ts
import { render } from "npm:@react-email/render@^2.1.0";
import { createElement } from "npm:react@^19.2.7";

// packages/email/src/brand/tokens.ts
var TEXT_SKIP_CLASS = "octant-text-skip";
var colors = {
  /** Outermost page background. */
  base: "#0a0a0a",
  /** Card / content background. */
  surface: "#111111",
  /** Nested surfaces: code blocks, info rows, callouts. */
  surface2: "#1a1a1a",
  /** Default hairline border. */
  edge: "#222222",
  /** Emphasised border. */
  edge2: "#333333",
  /** Primary text. */
  ink: "#ededed",
  /** Body copy. */
  ink2: "#cccccc",
  /** Secondary copy. */
  ink3: "#aaaaaa",
  /** Labels and metadata. */
  muted: "#888888",
  /** Footer / legal text. */
  faint: "#666666",
  /** Brand accent (from favicon.svg). */
  accent: "#863bff",
  /** Accent, pressed/darker variant. */
  accentDeep: "#7e14ff",
  /** Text on top of the accent. */
  accentInk: "#ffffff",
  /** Status colours, taken from `src/modules/metrics/chartTheme.ts` so charts and email agree. */
  success: "#0ca30c",
  warning: "#fab219",
  danger: "#d03b3b",
  info: "#3987e5"
};
var fonts = {
  /** Identical to `body { font-family }` in src/styles/index.css. */
  sans: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  /** For tokens and one-time codes. */
  mono: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace"
};
var fontSizes = {
  xs: "12px",
  sm: "14px",
  base: "16px",
  lg: "18px",
  xl: "22px",
  xxl: "28px"
};
var spacing = {
  xs: "4px",
  sm: "8px",
  md: "16px",
  lg: "24px",
  xl: "32px",
  xxl: "48px"
};
var radii = {
  sm: "6px",
  md: "10px",
  lg: "14px",
  pill: "999px"
};
var layout = {
  contentWidth: "600px",
  /** Outlook ignores `max-width`, so tables also carry this as an explicit `width`. */
  contentWidthPx: 600
};
var toneStyles = {
  neutral: { border: colors.edge2, text: colors.ink2, background: colors.surface2 },
  success: { border: "#1c4a1c", text: "#7ee07e", background: "#0e1f0e" },
  warning: { border: "#5a4410", text: "#f5cd6a", background: "#211a08" },
  danger: { border: "#5a1f1f", text: "#f08a8a", background: "#210e0e" },
  info: { border: "#1d3a5c", text: "#8ec1f5", background: "#0c1724" }
};

// packages/email/src/templates/transactional/BillingSuccess.tsx
import { Section as Section5 } from "npm:@react-email/components@^1.0.12";

// packages/email/src/brand/urls.ts
function join(origin, path) {
  const suffix = path.startsWith("/") ? path : `/${path}`;
  return `${origin.replace(/\/+$/, "")}${suffix}`;
}
function createUrls(appUrl) {
  return {
    dashboard: join(appUrl, "/"),
    settings: join(appUrl, "/settings"),
    // The plan card lives on the settings page; keep the deep link honest rather than inventing a route.
    billing: join(appUrl, "/settings?tab=plan"),
    security: join(appUrl, "/settings?tab=security"),
    login: join(appUrl, "/login"),
    forgotPassword: join(appUrl, "/forgot-password"),
    preferences: (token) => join(appUrl, `/settings?prefs=${encodeURIComponent(token)}`),
    path: (path) => join(appUrl, path)
  };
}
function urlsFor(brand) {
  return createUrls(brand.appUrl);
}

// packages/email/src/templates/components/ActionButton.tsx
import { Button } from "npm:@react-email/components@^1.0.12";
import { jsx } from "npm:react@^19.2.7/jsx-runtime";
var base = {
  fontFamily: fonts.sans,
  fontSize: fontSizes.sm,
  fontWeight: 600,
  lineHeight: "20px",
  textDecoration: "none",
  textAlign: "center",
  borderRadius: radii.sm,
  // Vertical padding on an <a> is unreliable in Outlook; React Email compensates internally, and the
  // explicit padding here is what every other client uses.
  padding: "12px 22px",
  display: "inline-block"
};
var variants = {
  primary: {
    backgroundColor: colors.accent,
    color: colors.accentInk,
    border: `1px solid ${colors.accent}`
  },
  neutral: {
    backgroundColor: colors.surface2,
    color: colors.ink,
    border: `1px solid ${colors.edge2}`
  },
  danger: {
    backgroundColor: colors.danger,
    color: "#ffffff",
    border: `1px solid ${colors.danger}`
  }
};
function ActionButton({ href, children, variant = "primary" }) {
  return /* @__PURE__ */ jsx(Button, { href, style: { ...base, ...variants[variant] }, children });
}

// packages/email/src/templates/components/InfoTable.tsx
import { Section } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx2, jsxs } from "npm:react@^19.2.7/jsx-runtime";
var cellBase = {
  fontFamily: fonts.sans,
  fontSize: fontSizes.sm,
  lineHeight: "22px",
  padding: "7px 0",
  verticalAlign: "top"
};
function InfoTable({ rows }) {
  const visible = rows.filter(
    (row) => row.value !== void 0 && row.value !== ""
  );
  if (visible.length === 0) return null;
  return /* @__PURE__ */ jsx2(
    Section,
    {
      style: {
        backgroundColor: colors.surface2,
        border: `1px solid ${colors.edge}`,
        borderRadius: radii.md,
        padding: `${spacing.sm} ${spacing.md}`,
        margin: `0 0 ${spacing.md}`
      },
      children: /* @__PURE__ */ jsx2("table", { role: "presentation", width: "100%", cellPadding: 0, cellSpacing: 0, style: { width: "100%" }, children: /* @__PURE__ */ jsx2("tbody", { children: visible.map((row) => /* @__PURE__ */ jsxs("tr", { children: [
        /* @__PURE__ */ jsx2("td", { style: { ...cellBase, color: colors.muted, width: "42%" }, children: row.label }),
        /* @__PURE__ */ jsx2("td", { style: { ...cellBase, color: colors.ink2, fontWeight: 500 }, children: String(row.value) })
      ] }, row.label)) }) })
    }
  );
}

// packages/email/src/templates/components/typography.tsx
import { Heading, Text } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx3 } from "npm:react@^19.2.7/jsx-runtime";
var headingBase = {
  fontFamily: fonts.sans,
  color: colors.ink,
  letterSpacing: "-0.02em",
  fontWeight: 600,
  margin: `0 0 ${spacing.md}`
};
function EmailHeading({ children, level = 1, style }) {
  const sized = {
    ...headingBase,
    fontSize: level === 1 ? fontSizes.xxl : fontSizes.xl,
    lineHeight: level === 1 ? "34px" : "28px",
    ...style
  };
  return /* @__PURE__ */ jsx3(Heading, { as: level === 1 ? "h1" : "h2", style: sized, children });
}
var paragraphTones = {
  default: { fontSize: fontSizes.base, lineHeight: "26px", color: colors.ink2 },
  muted: { fontSize: fontSizes.sm, lineHeight: "22px", color: colors.muted },
  small: { fontSize: fontSizes.xs, lineHeight: "20px", color: colors.faint }
};
function Paragraph({ children, tone = "default", style }) {
  return /* @__PURE__ */ jsx3(
    Text,
    {
      style: {
        fontFamily: fonts.sans,
        margin: `0 0 ${spacing.md}`,
        ...paragraphTones[tone],
        ...style
      },
      children
    }
  );
}
function Label({ children }) {
  return /* @__PURE__ */ jsx3(
    Text,
    {
      style: {
        fontFamily: fonts.sans,
        fontSize: "11px",
        lineHeight: "16px",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        color: colors.faint,
        margin: `0 0 ${spacing.sm}`
      },
      children
    }
  );
}

// packages/email/src/templates/layouts/BaseLayout.tsx
import { Body, Container, Head, Html, Preview, Section as Section4 } from "npm:@react-email/components@^1.0.12";

// packages/email/src/templates/layouts/Footer.tsx
import { Link, Section as Section2, Text as Text2 } from "npm:@react-email/components@^1.0.12";

// packages/email/src/templates/components/Divider.tsx
import { Hr } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx4 } from "npm:react@^19.2.7/jsx-runtime";
function Divider({ compact = false }) {
  return /* @__PURE__ */ jsx4(
    Hr,
    {
      style: {
        border: "none",
        borderTop: `1px solid ${colors.edge}`,
        margin: `${compact ? spacing.md : spacing.lg} 0`,
        width: "100%"
      }
    }
  );
}

// packages/email/src/templates/layouts/Footer.tsx
import { Fragment, jsx as jsx5, jsxs as jsxs2 } from "npm:react@^19.2.7/jsx-runtime";
var line = {
  fontFamily: fonts.sans,
  fontSize: fontSizes.xs,
  lineHeight: "20px",
  color: colors.faint,
  margin: `0 0 ${spacing.xs}`
};
var link = {
  color: colors.muted,
  textDecoration: "underline"
};
function Footer({ brand }) {
  return /* @__PURE__ */ jsxs2(Section2, { style: { padding: `0 0 ${spacing.xl}` }, children: [
    /* @__PURE__ */ jsx5(Divider, {}),
    /* @__PURE__ */ jsxs2(Text2, { style: line, children: [
      "Questions? Reach us at",
      " ",
      /* @__PURE__ */ jsx5(Link, { href: `mailto:${brand.supportEmail}`, style: link, children: brand.supportEmail }),
      "."
    ] }),
    /* @__PURE__ */ jsxs2(Text2, { style: line, children: [
      "You received this because it relates to your ",
      brand.appName,
      " account. We only send transactional email \u2014 never marketing.",
      brand.preferencesUrl !== void 0 && /* @__PURE__ */ jsxs2(Fragment, { children: [
        " ",
        /* @__PURE__ */ jsx5(Link, { href: brand.preferencesUrl, style: link, children: "Manage notification preferences" }),
        "."
      ] })
    ] }),
    /* @__PURE__ */ jsxs2(Text2, { style: line, children: [
      "\xA9 ",
      brand.appName
    ] })
  ] });
}

// packages/email/src/templates/layouts/Header.tsx
import { Section as Section3 } from "npm:@react-email/components@^1.0.12";

// packages/email/src/templates/components/Logo.tsx
import { Column, Row, Text as Text3 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx6, jsxs as jsxs3 } from "npm:react@^19.2.7/jsx-runtime";
var tileCell = {
  width: "32px",
  verticalAlign: "middle"
};
var tile = {
  margin: "0",
  width: "32px",
  height: "32px",
  lineHeight: "32px",
  textAlign: "center",
  backgroundColor: colors.accent,
  color: colors.accentInk,
  borderRadius: radii.sm,
  fontFamily: fonts.sans,
  fontSize: fontSizes.lg,
  fontWeight: 600
};
var wordmarkCell = {
  paddingLeft: "10px",
  verticalAlign: "middle"
};
var wordmark = {
  margin: "0",
  fontFamily: fonts.sans,
  fontSize: fontSizes.lg,
  fontWeight: 600,
  letterSpacing: "-0.01em",
  color: colors.ink
};
function Logo({ appName }) {
  return /* @__PURE__ */ jsxs3(Row, { children: [
    /* @__PURE__ */ jsx6(Column, { style: tileCell, children: /* @__PURE__ */ jsx6(Text3, { className: TEXT_SKIP_CLASS, style: tile, children: appName.charAt(0).toUpperCase() }) }),
    /* @__PURE__ */ jsx6(Column, { style: wordmarkCell, children: /* @__PURE__ */ jsx6(Text3, { style: wordmark, children: appName }) })
  ] });
}

// packages/email/src/templates/layouts/Header.tsx
import { jsx as jsx7 } from "npm:react@^19.2.7/jsx-runtime";
function Header({ brand }) {
  return /* @__PURE__ */ jsx7(Section3, { style: { padding: `${spacing.lg} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsx7(Logo, { appName: brand.appName }) });
}

// packages/email/src/templates/layouts/BaseLayout.tsx
import { jsx as jsx8, jsxs as jsxs4 } from "npm:react@^19.2.7/jsx-runtime";
var body = {
  backgroundColor: colors.base,
  color: colors.ink2,
  fontFamily: fonts.sans,
  margin: "0",
  padding: "0",
  WebkitFontSmoothing: "antialiased"
};
var container = {
  width: layout.contentWidth,
  maxWidth: layout.contentWidth,
  margin: "0 auto",
  padding: `0 ${spacing.lg}`,
  backgroundColor: colors.base
};
var card = {
  backgroundColor: colors.surface,
  border: `1px solid ${colors.edge}`,
  borderRadius: radii.lg,
  padding: spacing.xl
};
function BaseLayout({ preview, brand, children }) {
  return /* @__PURE__ */ jsxs4(Html, { lang: "en", dir: "ltr", children: [
    /* @__PURE__ */ jsxs4(Head, { children: [
      /* @__PURE__ */ jsx8("meta", { name: "color-scheme", content: "dark" }),
      /* @__PURE__ */ jsx8("meta", { name: "supported-color-schemes", content: "dark" })
    ] }),
    /* @__PURE__ */ jsx8(Preview, { children: preview }),
    /* @__PURE__ */ jsx8(Body, { style: body, children: /* @__PURE__ */ jsxs4(Container, { style: container, children: [
      /* @__PURE__ */ jsx8(Header, { brand }),
      /* @__PURE__ */ jsx8(Section4, { style: card, children }),
      /* @__PURE__ */ jsx8(Footer, { brand })
    ] }) })
  ] });
}

// packages/email/src/templates/greeting.ts
function greetingFor(name) {
  const trimmed = name?.trim();
  return trimmed !== void 0 && trimmed !== "" ? `Hi ${trimmed},` : "Hi there,";
}
function pluralize(count, singular, plural = `${singular}s`) {
  return `${count} ${Math.abs(count) === 1 ? singular : plural}`;
}
function expiryNote(minutes) {
  if (minutes === void 0 || minutes <= 0) return void 0;
  if (minutes % 60 === 0) return `This link expires in ${pluralize(minutes / 60, "hour")}.`;
  return `This link expires in ${pluralize(minutes, "minute")}.`;
}

// packages/email/src/templates/preview.ts
var previewBrand = {
  appName: "Octant",
  appUrl: "https://app.useoctant.com",
  supportEmail: "support@useoctant.com",
  preferencesUrl: "https://app.useoctant.com/settings?prefs=preview-token"
};
function withPreview(component, previewProps) {
  const previewable = component;
  previewable.PreviewProps = previewProps;
  return previewable;
}

// packages/email/src/templates/transactional/BillingSuccess.tsx
import { jsx as jsx9, jsxs as jsxs5 } from "npm:react@^19.2.7/jsx-runtime";
function BillingSuccess({
  name,
  planName,
  amountFormatted,
  invoiceNumber,
  invoiceUrl,
  periodEnd,
  brand
}) {
  const urls = urlsFor(brand);
  return /* @__PURE__ */ jsxs5(BaseLayout, { preview: `Payment received \u2014 ${amountFormatted} for ${brand.appName} ${planName}.`, brand, children: [
    /* @__PURE__ */ jsx9(EmailHeading, { children: "Payment received" }),
    /* @__PURE__ */ jsx9(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs5(Paragraph, { children: [
      "Thanks \u2014 we've received your payment and your ",
      planName,
      " plan is active."
    ] }),
    /* @__PURE__ */ jsx9(
      InfoTable,
      {
        rows: [
          { label: "Plan", value: planName },
          { label: "Amount", value: amountFormatted },
          { label: "Invoice", value: invoiceNumber },
          { label: "Paid through", value: periodEnd }
        ]
      }
    ),
    /* @__PURE__ */ jsx9(Section5, { style: { padding: `${spacing.xs} 0 0` }, children: /* @__PURE__ */ jsx9(ActionButton, { href: invoiceUrl ?? urls.billing, variant: invoiceUrl !== void 0 ? "primary" : "neutral", children: invoiceUrl !== void 0 ? "View receipt" : "Manage billing" }) })
  ] });
}
var BillingSuccessPreview = withPreview(BillingSuccess, {
  name: "Ana",
  planName: "Pro",
  amountFormatted: "R$ 49,00",
  invoiceNumber: "B1C2D3-0007",
  invoiceUrl: "https://invoice.stripe.com/i/preview",
  periodEnd: "3 Sep 2026",
  brand: previewBrand
});

// packages/email/src/templates/transactional/EmailChanged.tsx
import { Section as Section8 } from "npm:@react-email/components@^1.0.12";

// packages/email/src/templates/components/Callout.tsx
import { Section as Section6 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx10, jsxs as jsxs6 } from "npm:react@^19.2.7/jsx-runtime";
function Callout({ children, tone = "neutral", title }) {
  const palette = toneStyles[tone];
  return /* @__PURE__ */ jsxs6(
    Section6,
    {
      style: {
        backgroundColor: palette.background,
        border: `1px solid ${palette.border}`,
        borderRadius: radii.md,
        padding: spacing.md,
        margin: `0 0 ${spacing.md}`
      },
      children: [
        title !== void 0 && /* @__PURE__ */ jsx10(
          "p",
          {
            style: {
              fontFamily: fonts.sans,
              fontSize: fontSizes.sm,
              fontWeight: 600,
              lineHeight: "20px",
              color: palette.text,
              margin: `0 0 ${spacing.xs}`
            },
            children: title
          }
        ),
        /* @__PURE__ */ jsx10(
          "div",
          {
            style: {
              fontFamily: fonts.sans,
              fontSize: fontSizes.sm,
              lineHeight: "22px",
              color: palette.text
            },
            children
          }
        )
      ]
    }
  );
}

// packages/email/src/templates/components/TokenBlock.tsx
import { Link as Link2, Section as Section7, Text as Text4 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx11 } from "npm:react@^19.2.7/jsx-runtime";
function TokenBlock({ value, href, emphasis = "url" }) {
  const isCode = emphasis === "code";
  const inner = {
    fontFamily: fonts.mono,
    fontSize: isCode ? fontSizes.xl : fontSizes.xs,
    lineHeight: isCode ? "30px" : "20px",
    letterSpacing: isCode ? "0.22em" : "normal",
    color: isCode ? colors.ink : colors.ink3,
    textAlign: isCode ? "center" : "left",
    wordBreak: "break-all",
    margin: "0",
    textDecoration: "none"
  };
  return /* @__PURE__ */ jsx11(
    Section7,
    {
      style: {
        backgroundColor: colors.surface2,
        border: `1px solid ${colors.edge2}`,
        borderRadius: radii.md,
        padding: isCode ? spacing.md : "12px",
        margin: `0 0 ${spacing.md}`
      },
      children: href === void 0 ? /* @__PURE__ */ jsx11(Text4, { style: inner, children: value }) : /* @__PURE__ */ jsx11(Link2, { href, style: inner, children: value })
    }
  );
}

// packages/email/src/templates/components/FallbackLink.tsx
import { Fragment as Fragment2, jsx as jsx12, jsxs as jsxs7 } from "npm:react@^19.2.7/jsx-runtime";
function FallbackLink({ url, token, label }) {
  return /* @__PURE__ */ jsxs7(Fragment2, { children: [
    /* @__PURE__ */ jsx12(Paragraph, { tone: "muted", children: label ?? "If the button doesn't work, copy and paste this link into your browser:" }),
    /* @__PURE__ */ jsx12(TokenBlock, { value: url, href: url, emphasis: "url" }),
    token !== void 0 && /* @__PURE__ */ jsxs7(Fragment2, { children: [
      /* @__PURE__ */ jsx12(Paragraph, { tone: "muted", children: "Or enter this code manually:" }),
      /* @__PURE__ */ jsx12(TokenBlock, { value: token, emphasis: "code" })
    ] })
  ] });
}

// packages/email/src/templates/transactional/EmailChanged.tsx
import { Fragment as Fragment3, jsx as jsx13, jsxs as jsxs8 } from "npm:react@^19.2.7/jsx-runtime";
function EmailChanged({
  name,
  newEmail,
  oldEmail,
  confirmUrl,
  occurredAt,
  ipAddress,
  userAgent,
  location,
  brand
}) {
  const urls = urlsFor(brand);
  const isConfirmation = confirmUrl !== void 0;
  return /* @__PURE__ */ jsxs8(
    BaseLayout,
    {
      preview: isConfirmation ? `Confirm ${newEmail} as your new ${brand.appName} email.` : `Your ${brand.appName} email address was changed.`,
      brand,
      children: [
        /* @__PURE__ */ jsx13(EmailHeading, { children: isConfirmation ? "Confirm your new email" : "Your email address changed" }),
        /* @__PURE__ */ jsx13(Paragraph, { children: greetingFor(name) }),
        /* @__PURE__ */ jsx13(Paragraph, { children: isConfirmation ? `Confirm this address to start using it to sign in to ${brand.appName}.` : `The email address on your ${brand.appName} account was changed. Sign in with the new address from now on.` }),
        /* @__PURE__ */ jsx13(
          InfoTable,
          {
            rows: [
              { label: "Previous address", value: oldEmail },
              { label: "New address", value: newEmail },
              { label: "When", value: occurredAt },
              { label: "IP address", value: ipAddress },
              { label: "Location", value: location },
              { label: "Device", value: userAgent }
            ]
          }
        ),
        isConfirmation ? /* @__PURE__ */ jsxs8(Fragment3, { children: [
          /* @__PURE__ */ jsx13(Section8, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsx13(ActionButton, { href: confirmUrl, children: "Confirm this address" }) }),
          /* @__PURE__ */ jsx13(FallbackLink, { url: confirmUrl }),
          /* @__PURE__ */ jsx13(Paragraph, { tone: "muted", children: "Until you confirm, your old address stays active and nothing changes." })
        ] }) : /* @__PURE__ */ jsxs8(Fragment3, { children: [
          /* @__PURE__ */ jsx13(Callout, { tone: "danger", title: "Didn't make this change?", children: "Someone else may have access to your account. Reset your password now \u2014 you'll be able to recover the account from this address." }),
          /* @__PURE__ */ jsx13(Section8, { style: { padding: `${spacing.xs} 0 0` }, children: /* @__PURE__ */ jsx13(ActionButton, { href: urls.forgotPassword, variant: "danger", children: "Reset my password" }) })
        ] })
      ]
    }
  );
}
var EmailChangedPreview = withPreview(EmailChanged, {
  name: "Ana",
  newEmail: "ana.souza@example.com",
  oldEmail: "ana@example.com",
  confirmUrl: "https://app.useoctant.com/auth/callback?token_hash=preview&type=email_change",
  occurredAt: "4 Aug 2026 at 14:32 UTC",
  ipAddress: "203.0.113.42",
  location: "S\xE3o Paulo, BR",
  userAgent: "Chrome on macOS",
  brand: previewBrand
});

// packages/email/src/templates/transactional/Invitation.tsx
import { Section as Section9 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx14, jsxs as jsxs9 } from "npm:react@^19.2.7/jsx-runtime";
function Invitation({
  inviteUrl,
  inviterName,
  inviterEmail,
  workspaceName,
  expiresInDays,
  brand
}) {
  const inviter = inviterName ?? inviterEmail;
  const destination = workspaceName ?? brand.appName;
  const headline = workspaceName !== void 0 ? `Join ${workspaceName}` : `You're invited to ${brand.appName}`;
  return /* @__PURE__ */ jsxs9(
    BaseLayout,
    {
      preview: inviter !== void 0 ? `${inviter} invited you to ${destination}.` : `You've been invited to ${destination}.`,
      brand,
      children: [
        /* @__PURE__ */ jsx14(EmailHeading, { children: headline }),
        /* @__PURE__ */ jsxs9(Paragraph, { children: [
          inviter !== void 0 ? `${inviter} invited you to ` : "You have been invited to ",
          "join ",
          destination,
          " on ",
          brand.appName,
          " \u2014 one master record of your career, turned into a r\xE9sum\xE9 tailored to every role you apply for."
        ] }),
        /* @__PURE__ */ jsx14(Section9, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsx14(ActionButton, { href: inviteUrl, children: "Accept invitation" }) }),
        expiresInDays !== void 0 && expiresInDays > 0 && /* @__PURE__ */ jsxs9(Paragraph, { tone: "muted", children: [
          "This invitation expires in ",
          pluralize(expiresInDays, "day"),
          "."
        ] }),
        /* @__PURE__ */ jsx14(FallbackLink, { url: inviteUrl }),
        /* @__PURE__ */ jsx14(Paragraph, { tone: "muted", children: "Not expecting this? You can ignore this email and no account will be created." })
      ]
    }
  );
}
var InvitationPreview = withPreview(Invitation, {
  inviteUrl: "https://app.useoctant.com/auth/callback?token_hash=preview&type=invite",
  inviterName: "Ana Souza",
  inviterEmail: "ana@example.com",
  workspaceName: "Acme Talent",
  expiresInDays: 7,
  brand: previewBrand
});

// packages/email/src/templates/transactional/MagicLink.tsx
import { Section as Section10 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx15, jsxs as jsxs10 } from "npm:react@^19.2.7/jsx-runtime";
function MagicLink({
  name,
  magicLinkUrl,
  token,
  expiresInMinutes,
  brand
}) {
  const expiry = expiryNote(expiresInMinutes);
  return /* @__PURE__ */ jsxs10(BaseLayout, { preview: `Your sign-in link for ${brand.appName}.`, brand, children: [
    /* @__PURE__ */ jsxs10(EmailHeading, { children: [
      "Sign in to ",
      brand.appName
    ] }),
    /* @__PURE__ */ jsx15(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsx15(Paragraph, { children: "No password needed \u2014 this link signs you straight in." }),
    /* @__PURE__ */ jsx15(Section10, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsx15(ActionButton, { href: magicLinkUrl, children: "Sign in" }) }),
    expiry !== void 0 && /* @__PURE__ */ jsx15(Paragraph, { tone: "muted", children: expiry }),
    /* @__PURE__ */ jsx15(FallbackLink, { url: magicLinkUrl, token }),
    /* @__PURE__ */ jsx15(Callout, { tone: "info", title: "Keep this link private", children: "Anyone with this link can sign in as you until it expires or is used. Don't forward this email." })
  ] });
}
var MagicLinkPreview = withPreview(MagicLink, {
  name: "Ana",
  magicLinkUrl: "https://app.useoctant.com/auth/callback?token_hash=preview&type=magiclink",
  token: "739104",
  expiresInMinutes: 15,
  brand: previewBrand
});

// packages/email/src/templates/transactional/PasswordChanged.tsx
import { Section as Section11 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx16, jsxs as jsxs11 } from "npm:react@^19.2.7/jsx-runtime";
function PasswordChanged({
  name,
  occurredAt,
  ipAddress,
  userAgent,
  location,
  resetUrl,
  brand
}) {
  const urls = urlsFor(brand);
  return /* @__PURE__ */ jsxs11(BaseLayout, { preview: `Your ${brand.appName} password was changed.`, brand, children: [
    /* @__PURE__ */ jsx16(EmailHeading, { children: "Your password was changed" }),
    /* @__PURE__ */ jsx16(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs11(Paragraph, { children: [
      "The password on your ",
      brand.appName,
      " account was updated successfully. All other sessions were signed out."
    ] }),
    /* @__PURE__ */ jsx16(
      InfoTable,
      {
        rows: [
          { label: "When", value: occurredAt },
          { label: "IP address", value: ipAddress },
          { label: "Location", value: location },
          { label: "Device", value: userAgent }
        ]
      }
    ),
    /* @__PURE__ */ jsx16(Callout, { tone: "warning", title: "Wasn't you?", children: "Someone else may know your credentials. Reset the password immediately and review the devices signed in to your account." }),
    /* @__PURE__ */ jsx16(Section11, { style: { padding: `${spacing.xs} 0 0` }, children: /* @__PURE__ */ jsx16(ActionButton, { href: resetUrl ?? urls.forgotPassword, variant: "danger", children: "Reset my password" }) })
  ] });
}
var PasswordChangedPreview = withPreview(PasswordChanged, {
  name: "Ana",
  occurredAt: "4 Aug 2026 at 14:32 UTC",
  ipAddress: "203.0.113.42",
  location: "S\xE3o Paulo, BR",
  userAgent: "Chrome on macOS",
  brand: previewBrand
});

// packages/email/src/templates/transactional/PasswordReset.tsx
import { Section as Section12 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx17, jsxs as jsxs12 } from "npm:react@^19.2.7/jsx-runtime";
function PasswordReset({
  name,
  resetUrl,
  token,
  expiresInMinutes,
  occurredAt,
  ipAddress,
  userAgent,
  location,
  brand
}) {
  const expiry = expiryNote(expiresInMinutes);
  return /* @__PURE__ */ jsxs12(BaseLayout, { preview: `Reset your ${brand.appName} password.`, brand, children: [
    /* @__PURE__ */ jsx17(EmailHeading, { children: "Reset your password" }),
    /* @__PURE__ */ jsx17(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs12(Paragraph, { children: [
      "Someone asked to reset the password for your ",
      brand.appName,
      " account. Use the button below to choose a new one."
    ] }),
    /* @__PURE__ */ jsx17(Section12, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsx17(ActionButton, { href: resetUrl, children: "Choose a new password" }) }),
    expiry !== void 0 && /* @__PURE__ */ jsx17(Paragraph, { tone: "muted", children: expiry }),
    /* @__PURE__ */ jsx17(
      InfoTable,
      {
        rows: [
          { label: "Requested", value: occurredAt },
          { label: "IP address", value: ipAddress },
          { label: "Location", value: location },
          { label: "Device", value: userAgent }
        ]
      }
    ),
    /* @__PURE__ */ jsx17(FallbackLink, { url: resetUrl, token }),
    /* @__PURE__ */ jsx17(Callout, { tone: "warning", title: "Didn't request this?", children: "Your password hasn't changed and this link will expire on its own. If you'd like to be certain, sign in and change your password \u2014 that invalidates every outstanding reset link." })
  ] });
}
var PasswordResetPreview = withPreview(PasswordReset, {
  name: "Ana",
  resetUrl: "https://app.useoctant.com/reset-password?token_hash=preview&type=recovery",
  token: "204817",
  expiresInMinutes: 60,
  occurredAt: "4 Aug 2026 at 14:32 UTC",
  ipAddress: "203.0.113.42",
  location: "S\xE3o Paulo, BR",
  userAgent: "Chrome on macOS",
  brand: previewBrand
});

// packages/email/src/templates/transactional/PaymentFailed.tsx
import { Section as Section13 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx18, jsxs as jsxs13 } from "npm:react@^19.2.7/jsx-runtime";
function PaymentFailed({
  name,
  amountFormatted,
  reason,
  nextAttemptOn,
  gracePeriodDays,
  brand
}) {
  const urls = urlsFor(brand);
  return /* @__PURE__ */ jsxs13(BaseLayout, { preview: `We couldn't process your ${brand.appName} payment.`, brand, children: [
    /* @__PURE__ */ jsx18(EmailHeading, { children: "Your payment didn't go through" }),
    /* @__PURE__ */ jsx18(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs13(Paragraph, { children: [
      "We tried to charge your card for your ",
      brand.appName,
      " subscription and it was declined. Updating your payment method takes about a minute and keeps your plan active."
    ] }),
    /* @__PURE__ */ jsx18(
      InfoTable,
      {
        rows: [
          { label: "Amount due", value: amountFormatted },
          { label: "Reason", value: reason },
          { label: "Next attempt", value: nextAttemptOn }
        ]
      }
    ),
    /* @__PURE__ */ jsx18(Section13, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsx18(ActionButton, { href: urls.billing, variant: "danger", children: "Update payment method" }) }),
    /* @__PURE__ */ jsx18(Callout, { tone: "warning", title: "What happens next", children: gracePeriodDays !== void 0 && gracePeriodDays > 0 ? `We'll retry automatically. If it still fails after ${pluralize(gracePeriodDays, "day")}, your account moves to the free plan \u2014 your data is kept either way.` : "We'll retry automatically. If it keeps failing, your account moves to the free plan \u2014 your data is kept either way." })
  ] });
}
var PaymentFailedPreview = withPreview(PaymentFailed, {
  name: "Ana",
  amountFormatted: "R$ 49,00",
  reason: "Your card was declined (insufficient funds)",
  nextAttemptOn: "7 Aug 2026",
  gracePeriodDays: 7,
  brand: previewBrand
});

// packages/email/src/templates/transactional/SecurityAlert.tsx
import { Section as Section14 } from "npm:@react-email/components@^1.0.12";

// packages/email/src/templates/props.ts
var SecurityAlertKind = {
  NewSignIn: "new_sign_in",
  NewDevice: "new_device",
  SuspiciousActivity: "suspicious_activity",
  Reauthentication: "reauthentication"
};

// packages/email/src/templates/transactional/SecurityAlert.tsx
import { Fragment as Fragment4, jsx as jsx19, jsxs as jsxs14 } from "npm:react@^19.2.7/jsx-runtime";
var COPY = {
  [SecurityAlertKind.NewSignIn]: {
    heading: "New sign-in to your account",
    lead: "Your account was just signed in to. If that was you, nothing more is needed."
  },
  [SecurityAlertKind.NewDevice]: {
    heading: "A new device signed in",
    lead: "Your account was signed in to from a device we haven\u2019t seen before."
  },
  [SecurityAlertKind.SuspiciousActivity]: {
    heading: "Unusual activity on your account",
    lead: "We noticed activity that doesn\u2019t match your usual pattern and wanted you to know right away."
  },
  [SecurityAlertKind.Reauthentication]: {
    heading: "Confirm it\u2019s you",
    lead: "Enter the code below to confirm this sensitive change."
  }
};
function SecurityAlert({
  name,
  kind,
  code,
  occurredAt,
  ipAddress,
  userAgent,
  location,
  secureAccountUrl,
  brand
}) {
  const urls = urlsFor(brand);
  const copy = COPY[kind];
  const isReauth = kind === SecurityAlertKind.Reauthentication;
  const tone = kind === SecurityAlertKind.SuspiciousActivity ? "danger" : "warning";
  return /* @__PURE__ */ jsxs14(BaseLayout, { preview: `${copy.heading} \u2014 ${brand.appName}`, brand, children: [
    /* @__PURE__ */ jsx19(EmailHeading, { children: copy.heading }),
    /* @__PURE__ */ jsx19(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsx19(Paragraph, { children: copy.lead }),
    isReauth && code !== void 0 && /* @__PURE__ */ jsx19(TokenBlock, { value: code, emphasis: "code" }),
    /* @__PURE__ */ jsx19(
      InfoTable,
      {
        rows: [
          { label: "When", value: occurredAt },
          { label: "IP address", value: ipAddress },
          { label: "Location", value: location },
          { label: "Device", value: userAgent }
        ]
      }
    ),
    !isReauth && /* @__PURE__ */ jsxs14(Fragment4, { children: [
      /* @__PURE__ */ jsx19(Callout, { tone, title: "If this wasn't you", children: "Change your password immediately. That signs out every other session and invalidates any outstanding reset links." }),
      /* @__PURE__ */ jsx19(Section14, { style: { padding: `${spacing.xs} 0 0` }, children: /* @__PURE__ */ jsx19(ActionButton, { href: secureAccountUrl ?? urls.security, variant: "danger", children: "Secure my account" }) })
    ] }),
    isReauth && /* @__PURE__ */ jsx19(Paragraph, { tone: "muted", children: "If you didn't start this, don't enter the code \u2014 and change your password as a precaution." })
  ] });
}
var SecurityAlertPreview = withPreview(SecurityAlert, {
  name: "Ana",
  kind: SecurityAlertKind.NewDevice,
  occurredAt: "4 Aug 2026 at 14:32 UTC",
  ipAddress: "203.0.113.42",
  location: "S\xE3o Paulo, BR",
  userAgent: "Safari on iPhone",
  brand: previewBrand
});

// packages/email/src/templates/transactional/SubscriptionCancelled.tsx
import { Section as Section15 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx20, jsxs as jsxs15 } from "npm:react@^19.2.7/jsx-runtime";
function SubscriptionCancelled({
  name,
  planName,
  accessUntil,
  brand
}) {
  const urls = urlsFor(brand);
  return /* @__PURE__ */ jsxs15(BaseLayout, { preview: `Your ${brand.appName} ${planName} subscription was cancelled.`, brand, children: [
    /* @__PURE__ */ jsx20(EmailHeading, { children: "Your subscription was cancelled" }),
    /* @__PURE__ */ jsx20(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs15(Paragraph, { children: [
      "Your ",
      planName,
      " subscription has been cancelled and you won't be charged again.",
      accessUntil !== void 0 ? " You keep full access until the end of the period you already paid for." : " Your account has moved to the free plan."
    ] }),
    /* @__PURE__ */ jsx20(
      InfoTable,
      {
        rows: [
          { label: "Plan", value: planName },
          { label: "Access until", value: accessUntil }
        ]
      }
    ),
    /* @__PURE__ */ jsx20(Callout, { tone: "info", title: "Your data stays put", children: "Nothing is deleted. Your Knowledge Base, jobs, applications and generated r\xE9sum\xE9s remain exactly as they are \u2014 the free plan only limits how many NEW jobs and r\xE9sum\xE9s you can create." }),
    /* @__PURE__ */ jsx20(Section15, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsxs15(ActionButton, { href: urls.billing, children: [
      "Reactivate ",
      planName
    ] }) }),
    /* @__PURE__ */ jsx20(Paragraph, { tone: "muted", children: "If you cancelled because something wasn't working, reply and tell us \u2014 we'd genuinely like to know." })
  ] });
}
var SubscriptionCancelledPreview = withPreview(SubscriptionCancelled, {
  name: "Ana",
  planName: "Pro",
  accessUntil: "3 Sep 2026",
  brand: previewBrand
});

// packages/email/src/templates/transactional/SubscriptionCreated.tsx
import { Section as Section16 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx21, jsxs as jsxs16 } from "npm:react@^19.2.7/jsx-runtime";
function SubscriptionCreated({
  name,
  planName,
  amountFormatted,
  interval,
  renewsOn,
  brand
}) {
  const urls = urlsFor(brand);
  const price = amountFormatted !== void 0 && interval !== void 0 ? `${amountFormatted} / ${interval}` : amountFormatted;
  return /* @__PURE__ */ jsxs16(BaseLayout, { preview: `Your ${brand.appName} ${planName} plan is live.`, brand, children: [
    /* @__PURE__ */ jsxs16(EmailHeading, { children: [
      "You're on ",
      planName
    ] }),
    /* @__PURE__ */ jsx21(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs16(Paragraph, { children: [
      "Your ",
      planName,
      " subscription is active. The limits are gone \u2014 add as many roles as you like and generate a tailored r\xE9sum\xE9 for every one of them."
    ] }),
    /* @__PURE__ */ jsx21(Label, { children: "What's included" }),
    /* @__PURE__ */ jsx21(
      InfoTable,
      {
        rows: [
          { label: "Job opportunities", value: "Unlimited" },
          { label: "Tailored r\xE9sum\xE9s", value: "Unlimited" },
          { label: "Discovery cadence", value: "Hourly instead of daily" }
        ]
      }
    ),
    /* @__PURE__ */ jsx21(Label, { children: "Your plan" }),
    /* @__PURE__ */ jsx21(
      InfoTable,
      {
        rows: [
          { label: "Plan", value: planName },
          { label: "Price", value: price },
          { label: "Renews", value: renewsOn }
        ]
      }
    ),
    /* @__PURE__ */ jsx21(Section16, { style: { padding: `${spacing.xs} 0 0` }, children: /* @__PURE__ */ jsxs16(ActionButton, { href: urls.dashboard, children: [
      "Start using ",
      planName
    ] }) }),
    /* @__PURE__ */ jsxs16(Paragraph, { tone: "muted", children: [
      "You can review or cancel your subscription any time from",
      " ",
      "billing settings: ",
      urls.billing
    ] })
  ] });
}
var SubscriptionCreatedPreview = withPreview(SubscriptionCreated, {
  name: "Ana",
  planName: "Pro",
  amountFormatted: "R$ 49,00",
  interval: "month",
  renewsOn: "3 Sep 2026",
  brand: previewBrand
});

// packages/email/src/templates/transactional/TrialEnding.tsx
import { Section as Section17 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx22, jsxs as jsxs17 } from "npm:react@^19.2.7/jsx-runtime";
function TrialEnding({
  name,
  planName,
  daysRemaining,
  trialEndsOn,
  brand
}) {
  const urls = urlsFor(brand);
  const remaining = pluralize(Math.max(0, daysRemaining), "day");
  return /* @__PURE__ */ jsxs17(BaseLayout, { preview: `Your ${brand.appName} trial ends in ${remaining}.`, brand, children: [
    /* @__PURE__ */ jsxs17(EmailHeading, { children: [
      "Your trial ends in ",
      remaining
    ] }),
    /* @__PURE__ */ jsx22(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs17(Paragraph, { children: [
      "Your ",
      planName,
      " trial is nearly over. Add a payment method to keep unlimited jobs and tailored r\xE9sum\xE9s \u2014 no interruption, nothing to migrate."
    ] }),
    /* @__PURE__ */ jsx22(
      InfoTable,
      {
        rows: [
          { label: "Plan", value: planName },
          { label: "Trial ends", value: trialEndsOn },
          { label: "Time remaining", value: remaining }
        ]
      }
    ),
    /* @__PURE__ */ jsx22(Section17, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsxs17(ActionButton, { href: urls.billing, children: [
      "Keep ",
      planName
    ] }) }),
    /* @__PURE__ */ jsx22(Callout, { tone: "neutral", title: "If you do nothing", children: "Your account simply moves to the free plan when the trial ends. Everything you've created stays \u2014 you'll just be limited on creating new jobs and r\xE9sum\xE9s." })
  ] });
}
var TrialEndingPreview = withPreview(TrialEnding, {
  name: "Ana",
  planName: "Pro",
  daysRemaining: 3,
  trialEndsOn: "7 Aug 2026",
  brand: previewBrand
});

// packages/email/src/templates/transactional/TrialExpired.tsx
import { Section as Section18 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx23, jsxs as jsxs18 } from "npm:react@^19.2.7/jsx-runtime";
function TrialExpired({ name, planName, brand }) {
  const urls = urlsFor(brand);
  return /* @__PURE__ */ jsxs18(BaseLayout, { preview: `Your ${brand.appName} trial has ended.`, brand, children: [
    /* @__PURE__ */ jsx23(EmailHeading, { children: "Your trial has ended" }),
    /* @__PURE__ */ jsx23(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs18(Paragraph, { children: [
      "Your ",
      planName,
      " trial is over and your account is now on the free plan. Everything you built is still there \u2014 nothing was deleted."
    ] }),
    /* @__PURE__ */ jsx23(Label, { children: "On the free plan" }),
    /* @__PURE__ */ jsx23(
      InfoTable,
      {
        rows: [
          { label: "Existing data", value: "Fully available" },
          { label: "New job opportunities", value: "Up to 3" },
          { label: "New tailored r\xE9sum\xE9s", value: "1" },
          { label: "Discovery cadence", value: "Daily" }
        ]
      }
    ),
    /* @__PURE__ */ jsx23(Section18, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsxs18(ActionButton, { href: urls.billing, children: [
      "Upgrade to ",
      planName
    ] }) }),
    /* @__PURE__ */ jsx23(Paragraph, { tone: "muted", children: "Upgrade whenever you like \u2014 the limits lift immediately and nothing needs re-doing." })
  ] });
}
var TrialExpiredPreview = withPreview(TrialExpired, { name: "Ana", planName: "Pro", brand: previewBrand });

// packages/email/src/templates/transactional/VerifyEmail.tsx
import { Section as Section19 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx24, jsxs as jsxs19 } from "npm:react@^19.2.7/jsx-runtime";
function VerifyEmail({
  name,
  verifyUrl,
  token,
  expiresInMinutes,
  brand
}) {
  const expiry = expiryNote(expiresInMinutes);
  return /* @__PURE__ */ jsxs19(BaseLayout, { preview: `Confirm your email to finish setting up ${brand.appName}.`, brand, children: [
    /* @__PURE__ */ jsx24(EmailHeading, { children: "Confirm your email" }),
    /* @__PURE__ */ jsx24(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs19(Paragraph, { children: [
      "Confirm this address to activate your ",
      brand.appName,
      " account. It takes one click."
    ] }),
    /* @__PURE__ */ jsx24(Section19, { style: { padding: `${spacing.xs} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsx24(ActionButton, { href: verifyUrl, children: "Confirm email address" }) }),
    expiry !== void 0 && /* @__PURE__ */ jsx24(Paragraph, { tone: "muted", children: expiry }),
    /* @__PURE__ */ jsx24(FallbackLink, { url: verifyUrl, token }),
    /* @__PURE__ */ jsx24(Paragraph, { tone: "muted", children: "If you didn't create an account, you can ignore this email \u2014 nothing was set up." })
  ] });
}
var VerifyEmailPreview = withPreview(VerifyEmail, {
  name: "Ana",
  verifyUrl: "https://app.useoctant.com/auth/callback?token_hash=preview&type=signup",
  token: "481920",
  expiresInMinutes: 60,
  brand: previewBrand
});

// packages/email/src/templates/transactional/Welcome.tsx
import { Section as Section20 } from "npm:@react-email/components@^1.0.12";
import { jsx as jsx25, jsxs as jsxs20 } from "npm:react@^19.2.7/jsx-runtime";
function Welcome({ name, brand }) {
  const urls = urlsFor(brand);
  return /* @__PURE__ */ jsxs20(BaseLayout, { preview: `Welcome to ${brand.appName} \u2014 here's how to get your first tailored r\xE9sum\xE9.`, brand, children: [
    /* @__PURE__ */ jsxs20(EmailHeading, { children: [
      "Welcome to ",
      brand.appName
    ] }),
    /* @__PURE__ */ jsx25(Paragraph, { children: greetingFor(name) }),
    /* @__PURE__ */ jsxs20(Paragraph, { children: [
      "Your account is ready. ",
      brand.appName,
      " keeps one master record of your career and turns it into a r\xE9sum\xE9 tailored to each role you apply for \u2014 so you stop rewriting the same bullets by hand."
    ] }),
    /* @__PURE__ */ jsx25(Label, { children: "Start here" }),
    /* @__PURE__ */ jsx25(
      InfoTable,
      {
        rows: [
          { label: "1 \xB7 Knowledge Base", value: "Add your roles, projects and achievements once" },
          { label: "2 \xB7 Add a job", value: "Paste a posting you actually want" },
          { label: "3 \xB7 Generate", value: "Get a r\xE9sum\xE9 matched to that posting" }
        ]
      }
    ),
    /* @__PURE__ */ jsx25(Section20, { style: { padding: `${spacing.sm} 0 ${spacing.md}` }, children: /* @__PURE__ */ jsxs20(ActionButton, { href: urls.dashboard, children: [
      "Open ",
      brand.appName
    ] }) }),
    /* @__PURE__ */ jsx25(Paragraph, { tone: "muted", children: "Not sure where to begin? Reply to this email \u2014 a real person reads it." })
  ] });
}
var WelcomePreview = withPreview(Welcome, { name: "Ana", brand: previewBrand });

// packages/email/src/registry.ts
var SECURITY_ALERT_SUBJECTS = {
  [SecurityAlertKind.NewSignIn]: "New sign-in to your account",
  [SecurityAlertKind.NewDevice]: "A new device signed in to your account",
  [SecurityAlertKind.SuspiciousActivity]: "Unusual activity on your account",
  [SecurityAlertKind.Reauthentication]: "Your confirmation code"
};
var templateRegistry = {
  welcome: {
    subject: (_props, brand) => `Welcome to ${brand.appName}`,
    component: Welcome,
    critical: true
  },
  "verify-email": {
    subject: (_props, brand) => `Confirm your email for ${brand.appName}`,
    component: VerifyEmail,
    critical: true
  },
  "password-reset": {
    subject: (_props, brand) => `Reset your ${brand.appName} password`,
    component: PasswordReset,
    critical: true
  },
  "magic-link": {
    subject: (_props, brand) => `Your ${brand.appName} sign-in link`,
    component: MagicLink,
    critical: true
  },
  invitation: {
    subject: (props, brand) => {
      const inviter = props.inviterName ?? props.inviterEmail;
      const destination = props.workspaceName ?? brand.appName;
      return inviter !== void 0 ? `${inviter} invited you to ${destination}` : `You're invited to ${destination}`;
    },
    component: Invitation,
    critical: true
  },
  "billing-success": {
    subject: (props, brand) => `Your ${brand.appName} receipt \u2014 ${props.amountFormatted}`,
    component: BillingSuccess,
    critical: true
  },
  "subscription-created": {
    subject: (props, brand) => `You're on ${brand.appName} ${props.planName}`,
    component: SubscriptionCreated,
    critical: true
  },
  "subscription-cancelled": {
    subject: (props) => `Your ${props.planName} subscription was cancelled`,
    component: SubscriptionCancelled,
    critical: true
  },
  "trial-ending": {
    subject: (props) => props.daysRemaining <= 0 ? "Your trial ends today" : `Your trial ends in ${pluralize(props.daysRemaining, "day")}`,
    component: TrialEnding,
    critical: true
  },
  "trial-expired": {
    subject: (_props, brand) => `Your ${brand.appName} trial has ended`,
    component: TrialExpired,
    critical: true
  },
  "payment-failed": {
    subject: () => "Your payment didn't go through",
    component: PaymentFailed,
    critical: true
  },
  "security-alert": {
    subject: (props) => SECURITY_ALERT_SUBJECTS[props.kind] ?? "Security alert on your account",
    component: SecurityAlert,
    critical: true
  },
  "email-changed": {
    subject: (props) => props.confirmUrl !== void 0 ? "Confirm your new email address" : "Your email address was changed",
    component: EmailChanged,
    critical: true
  },
  "password-changed": {
    subject: () => "Your password was changed",
    component: PasswordChanged,
    critical: true
  }
};
var TEMPLATE_NAMES = Object.keys(templateRegistry);

// packages/email/src/renderer.ts
var HTML_TO_TEXT_OPTIONS = {
  wordwrap: 78,
  selectors: [
    // Render label/value tables as aligned rows instead of one concatenated string.
    { selector: "table", format: "dataTable" },
    // Decorative-only nodes (the logo tile) add noise to a plain-text reading.
    { selector: `.${TEXT_SKIP_CLASS}`, format: "skip" },
    // `<img>` has no text value here — every image in these templates is decorative.
    { selector: "img", format: "skip" }
  ]
};
function createBrandContext(input) {
  return {
    appName: input.appName,
    appUrl: input.appUrl,
    supportEmail: input.supportEmail,
    preferencesUrl: input.preferencesUrl
  };
}
async function renderTemplate(name, props, brand) {
  const definition = templateRegistry[name];
  if (definition === void 0) {
    throw new EmailRenderError(`No template is registered under "${String(name)}".`);
  }
  const subject = definition.subject(props, brand);
  if (subject.trim() === "") {
    throw new EmailRenderError(`Template "${String(name)}" produced an empty subject.`);
  }
  try {
    const component = definition.component;
    const element = createElement(component, { ...props, brand });
    const [html, text] = await Promise.all([
      render(element),
      render(element, { plainText: true, htmlToTextOptions: HTML_TO_TEXT_OPTIONS })
    ]);
    if (html.trim() === "") throw new EmailRenderError(`Template "${String(name)}" produced empty HTML.`);
    return { subject, html, text };
  } catch (cause) {
    if (cause instanceof EmailRenderError) throw cause;
    const detail = cause instanceof Error ? cause.message : String(cause);
    throw new EmailRenderError(`Could not render the "${String(name)}" email. ${detail}`.trim(), { cause });
  }
}

// packages/email/src/transport/ResendTransport.ts
import { Resend } from "npm:resend@^6.18.1";
var PROVIDER = "resend";
var PERMANENT_CODES = /* @__PURE__ */ new Set([
  "validation_error",
  "missing_api_key",
  "restricted_api_key",
  "invalid_api_key",
  "not_found",
  "method_not_allowed",
  "invalid_attachment",
  "invalid_from_address",
  "invalid_access",
  "invalid_parameter",
  "invalid_region",
  "missing_required_field",
  "invalid_idempotency_key",
  "security_error"
]);
var TRANSIENT_CODES = /* @__PURE__ */ new Set([
  "application_error",
  "internal_server_error",
  // A concurrent replay of our own idempotency key: the first attempt is still in flight, so backing
  // off and asking again is exactly right.
  "concurrent_idempotent_requests"
]);
var RATE_LIMIT_CODES = /* @__PURE__ */ new Set(["rate_limit_exceeded", "daily_quota_exceeded", "monthly_quota_exceeded"]);
function parseRetryAfterMs(headers) {
  const raw = headers?.["retry-after"] ?? headers?.["Retry-After"];
  if (raw === void 0) return null;
  const seconds = Number(raw);
  return Number.isFinite(seconds) && seconds >= 0 ? seconds * 1e3 : null;
}
function toEmailError(error, headers, recipient) {
  const detail = `Resend rejected the message (${error.name}). ${error.message}`.trim();
  if (RATE_LIMIT_CODES.has(error.name)) {
    return new EmailRateLimitError(detail, {
      status: error.statusCode,
      providerCode: error.name,
      retryAfterMs: parseRetryAfterMs(headers)
    });
  }
  if (error.name === "validation_error" || error.name === "invalid_parameter" || error.name === "missing_required_field") {
    return new EmailValidationError(detail);
  }
  if (error.name === "security_error" && /suppress/i.test(error.message)) {
    return new EmailSuppressedError(recipient, { cause: new Error(detail) });
  }
  const retryable = TRANSIENT_CODES.has(error.name) ? true : PERMANENT_CODES.has(error.name) ? false : error.statusCode === null || error.statusCode >= 500 || error.statusCode === 408;
  return new EmailTransportError(detail, {
    status: error.statusCode,
    retryable,
    providerCode: error.name
  });
}
function toNetworkError(cause) {
  const message = cause instanceof Error ? cause.message : String(cause);
  return new EmailTransportError(`Could not reach Resend. ${message}`.trim(), {
    retryable: true,
    cause
  });
}
function createResendTransport(deps) {
  const client = deps.client ?? new Resend(deps.apiKey);
  return {
    name: PROVIDER,
    async send(email, options) {
      let response;
      try {
        response = await client.emails.send(
          {
            from: email.from,
            to: email.to,
            subject: email.subject,
            html: email.html,
            text: email.text,
            replyTo: email.replyTo,
            headers: email.headers,
            tags: email.tags
          },
          { idempotencyKey: options.idempotencyKey }
        );
      } catch (cause) {
        throw toNetworkError(cause);
      }
      if (response.error !== null) {
        throw toEmailError(response.error, response.headers, email.to);
      }
      return { id: response.data?.id ?? null, provider: PROVIDER };
    }
  };
}

// packages/email/src/transport/InMemoryTransport.ts
function createInMemoryTransport(name = "in-memory") {
  const sent = [];
  let attempts = 0;
  let pendingFailure = null;
  return {
    name,
    get sent() {
      return sent;
    },
    get attempts() {
      return attempts;
    },
    failWith(error, remaining = Number.POSITIVE_INFINITY) {
      pendingFailure = { error, remaining };
    },
    reset() {
      sent.length = 0;
      attempts = 0;
      pendingFailure = null;
    },
    send(email, options) {
      attempts += 1;
      if (pendingFailure !== null && pendingFailure.remaining > 0) {
        pendingFailure.remaining -= 1;
        const { error } = pendingFailure;
        if (pendingFailure.remaining <= 0) pendingFailure = null;
        return Promise.reject(error);
      }
      const replayed = sent.findIndex((record) => record.options.idempotencyKey === options.idempotencyKey);
      if (replayed !== -1) return Promise.resolve({ id: `in-memory-${replayed}`, provider: name });
      sent.push({ email, options });
      return Promise.resolve({ id: `in-memory-${sent.length - 1}`, provider: name });
    }
  };
}

// packages/email/src/transport/retry.ts
var DEFAULT_RETRY_POLICY = {
  attempts: 3,
  baseDelayMs: 300,
  maxDelayMs: 4e3
};
var defaultRetryDeps = {
  sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
  random: Math.random
};
function backoffDelay(attempt, policy, random) {
  const exponential = policy.baseDelayMs * 2 ** Math.max(0, attempt - 1);
  const capped = Math.min(policy.maxDelayMs, exponential);
  return Math.round(capped * (0.5 + 0.5 * random()));
}
function isRetryable(error) {
  if (error instanceof EmailTransportError) return error.retryable;
  if (error instanceof EmailError) return false;
  return true;
}
function delayFor(attempt, error, policy, random) {
  if (error instanceof EmailRateLimitError && error.retryAfterMs !== null) {
    return Math.min(error.retryAfterMs, policy.maxDelayMs);
  }
  return backoffDelay(attempt, policy, random);
}
async function withRetry(operation, policy = DEFAULT_RETRY_POLICY, deps = defaultRetryDeps, onRetry) {
  const attempts = Math.max(1, policy.attempts);
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await operation(attempt);
    } catch (error) {
      lastError = error;
      const isLastAttempt = attempt === attempts;
      if (isLastAttempt || !isRetryable(error)) throw error;
      const delayMs = delayFor(attempt, error, policy, deps.random);
      onRetry?.({ attempt, delayMs, error });
      await deps.sleep(delayMs);
    }
  }
  throw lastError;
}

// packages/email/src/EmailService.ts
var RECIPIENT_PATTERN = /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/;
var TAG_SAFE = /[^A-Za-z0-9_-]/g;
function hashKey(input) {
  let hash = 2166136261;
  for (let index = 0; index < input.length; index += 1) {
    hash ^= input.charCodeAt(index);
    hash = Math.imul(hash, 16777619) >>> 0;
  }
  return hash.toString(16).padStart(8, "0");
}
var EmailService = class {
  transport;
  config;
  retryPolicy;
  retryDeps;
  constructor(deps) {
    this.transport = deps.transport;
    this.config = deps.config;
    this.retryPolicy = deps.config.retry ?? DEFAULT_RETRY_POLICY;
    this.retryDeps = deps.retryDeps ?? defaultRetryDeps;
  }
  // ── Auth ────────────────────────────────────────────────────────────────────────────────────────
  sendWelcome(to, props, options) {
    return this.dispatch("welcome", to, props, options);
  }
  sendVerification(to, props, options) {
    return this.dispatch("verify-email", to, props, options);
  }
  sendPasswordReset(to, props, options) {
    return this.dispatch("password-reset", to, props, options);
  }
  sendMagicLink(to, props, options) {
    return this.dispatch("magic-link", to, props, options);
  }
  sendInvitation(to, props, options) {
    return this.dispatch("invitation", to, props, options);
  }
  // ── Account security ────────────────────────────────────────────────────────────────────────────
  sendSecurityAlert(to, props, options) {
    return this.dispatch("security-alert", to, props, options);
  }
  sendEmailChanged(to, props, options) {
    return this.dispatch("email-changed", to, props, options);
  }
  sendPasswordChanged(to, props, options) {
    return this.dispatch("password-changed", to, props, options);
  }
  // ── Billing ─────────────────────────────────────────────────────────────────────────────────────
  sendBillingSuccess(to, props, options) {
    return this.dispatch("billing-success", to, props, options);
  }
  sendSubscriptionCreated(to, props, options) {
    return this.dispatch("subscription-created", to, props, options);
  }
  sendSubscriptionCancelled(to, props, options) {
    return this.dispatch("subscription-cancelled", to, props, options);
  }
  sendTrialEnding(to, props, options) {
    return this.dispatch("trial-ending", to, props, options);
  }
  sendTrialExpired(to, props, options) {
    return this.dispatch("trial-expired", to, props, options);
  }
  sendPaymentFailed(to, props, options) {
    return this.dispatch("payment-failed", to, props, options);
  }
  // ── Internals ───────────────────────────────────────────────────────────────────────────────────
  /**
   * Escape hatch for callers that hold a template name as data (the auth hook maps Supabase's
   * `email_action_type` to one, the billing webhook maps a Stripe event type). Still fully typed: the
   * props must match the named template.
   */
  send(template, to, props, options) {
    return this.dispatch(template, to, props, options);
  }
  /** True when a real provider is wired up. Callers can skip building props when it isn't. */
  get isConfigured() {
    return this.config.apiKey !== void 0;
  }
  /**
   * The subject a send WOULD use, without rendering the body.
   *
   * Exists so a caller can write its `email_log` claim row (which needs a subject) BEFORE attempting
   * delivery. Claiming first is what makes the log an idempotency ledger rather than a post-hoc record:
   * the unique constraint on `idempotency_key` rejects the second concurrent attempt.
   */
  subjectFor(template, props, options) {
    return templateRegistry[template].subject(props, this.brandContext(options?.preferencesUrl));
  }
  brandContext(preferencesUrl) {
    return createBrandContext({
      appName: this.config.appName,
      appUrl: this.config.appUrl,
      supportEmail: this.config.supportEmail,
      preferencesUrl
    });
  }
  /**
   * Stable per-send key. Two sends collapse into one iff template, recipient/user and dedupeKey match.
   * The readable prefix is kept so the key is diagnosable in provider logs; the hash carries the rest.
   */
  buildIdempotencyKey(template, to, options) {
    const subject = options?.userId ?? to.toLowerCase();
    const dedupe = options?.dedupeKey ?? "default";
    return `${template}-${hashKey(`${template}:${subject}:${dedupe}`)}`;
  }
  async dispatch(template, to, props, options) {
    const recipient = to.trim();
    if (!RECIPIENT_PATTERN.test(recipient)) {
      throw new EmailValidationError(`"${to}" is not a valid email address.`);
    }
    const idempotencyKey = this.buildIdempotencyKey(template, recipient, options);
    const brand = this.brandContext(options?.preferencesUrl);
    const rendered = await renderTemplate(template, props, brand);
    const email = {
      to: recipient,
      from: this.config.from,
      replyTo: options?.replyTo ?? this.config.replyTo,
      subject: rendered.subject,
      html: rendered.html,
      text: rendered.text,
      headers: {
        // Tells conforming clients not to auto-reply (out-of-office) to transactional mail.
        "X-Auto-Response-Suppress": "All",
        "Auto-Submitted": "auto-generated"
      },
      tags: [{ name: "template", value: template.replace(TAG_SAFE, "_") }, ...options?.tags ?? []]
    };
    if (!this.isConfigured) {
      console.warn(`[email] skipping ${template} to ${recipient} \u2014 RESEND_API_KEY is not configured`);
      return {
        id: null,
        template,
        to: recipient,
        subject: rendered.subject,
        idempotencyKey,
        skipped: true,
        provider: "noop"
      };
    }
    try {
      const result = await withRetry(
        () => this.transport.send(email, { idempotencyKey }),
        this.retryPolicy,
        this.retryDeps,
        ({ attempt, delayMs, error }) => {
          const { code, message } = describeEmailError(error);
          console.warn(
            `[email] ${template} to ${recipient} failed (attempt ${attempt}), retrying in ${delayMs}ms: ${code} ${message}`
          );
        }
      );
      console.info(`[email] sent ${template} to ${recipient} (id: ${result.id ?? "none"})`);
      return {
        id: result.id,
        template,
        to: recipient,
        subject: rendered.subject,
        idempotencyKey,
        skipped: false,
        provider: result.provider
      };
    } catch (error) {
      const { code, message } = describeEmailError(error);
      console.error(`[email] ${template} to ${recipient} failed permanently: ${code} ${message}`);
      throw error;
    }
  }
};
function createEmailService(options) {
  options.warnings?.forEach((warning) => console.warn(`[email] ${warning}`));
  const transport = options.transport ?? (options.config.apiKey !== void 0 ? createResendTransport({ apiKey: options.config.apiKey }) : createInMemoryTransport("noop"));
  return new EmailService({ transport, config: options.config, retryDeps: options.retryDeps });
}

// packages/email/src/config.ts
var DEFAULTS = {
  appName: "Octant",
  domain: "useoctant.com",
  from: "Octant <noreply@useoctant.com>",
  supportEmail: "support@useoctant.com",
  /** Vite's dev server origin — only ever used locally, and always warned about. */
  appUrl: "http://localhost:5173"
};
var SENDER_PATTERN = /^(?:[^<>]*<\s*[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+\s*>|[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+)$/;
var ADDRESS_PATTERN = /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/;
function normalizeOrigin(value) {
  return value.trim().replace(/\/+$/, "");
}
function readPositiveInt(readEnv, key, fallback) {
  const raw = readEnv(key);
  if (raw === void 0 || raw === "") return fallback;
  const parsed = Number(raw);
  if (!Number.isFinite(parsed) || parsed < 0) {
    throw new EmailConfigError(`${key} must be a non-negative number. Got "${raw}".`);
  }
  return parsed;
}
function loadEmailConfig(readEnv) {
  const warnings = [];
  const read = (key) => {
    const value = readEnv(key);
    return value === void 0 || value.trim() === "" ? void 0 : value.trim();
  };
  const from = read("EMAIL_FROM") ?? DEFAULTS.from;
  if (!SENDER_PATTERN.test(from)) {
    throw new EmailConfigError(
      `EMAIL_FROM must be an email address or "Name <email@domain>". Got "${from}".`
    );
  }
  const replyTo = read("EMAIL_REPLY_TO");
  if (replyTo !== void 0 && !ADDRESS_PATTERN.test(replyTo)) {
    throw new EmailConfigError(`EMAIL_REPLY_TO must be a bare email address. Got "${replyTo}".`);
  }
  const supportEmail = read("EMAIL_SUPPORT") ?? DEFAULTS.supportEmail;
  if (!ADDRESS_PATTERN.test(supportEmail)) {
    throw new EmailConfigError(`EMAIL_SUPPORT must be a bare email address. Got "${supportEmail}".`);
  }
  const rawAppUrl = read("APP_URL");
  if (rawAppUrl === void 0) {
    warnings.push(
      `APP_URL is not set \u2014 links will point at ${DEFAULTS.appUrl}. Set it before sending real email.`
    );
  }
  const appUrl = normalizeOrigin(rawAppUrl ?? DEFAULTS.appUrl);
  const apiKey = read("RESEND_API_KEY");
  if (apiKey === void 0) {
    warnings.push("RESEND_API_KEY is not set \u2014 email sending is disabled and every send is a no-op.");
  }
  const retry = {
    attempts: readPositiveInt(readEnv, "EMAIL_RETRY_ATTEMPTS", DEFAULT_RETRY_POLICY.attempts),
    baseDelayMs: readPositiveInt(readEnv, "EMAIL_RETRY_BASE_DELAY_MS", DEFAULT_RETRY_POLICY.baseDelayMs),
    maxDelayMs: readPositiveInt(readEnv, "EMAIL_RETRY_MAX_DELAY_MS", DEFAULT_RETRY_POLICY.maxDelayMs)
  };
  return {
    config: {
      from,
      replyTo,
      appUrl,
      supportEmail,
      appName: read("EMAIL_APP_NAME") ?? DEFAULTS.appName,
      apiKey,
      retry
    },
    warnings,
    isConfigured: apiKey !== void 0
  };
}

// packages/email/src/integrations/supabaseAuth.ts
var AuthEmailAction = {
  Signup: "signup",
  Recovery: "recovery",
  MagicLink: "magiclink",
  Invite: "invite",
  EmailChange: "email_change",
  /** Sent to the address being LEFT, when "secure email change" is enabled. */
  EmailChangeCurrent: "email_change_current",
  /** Sent to the address being ADOPTED. */
  EmailChangeNew: "email_change_new",
  Reauthentication: "reauthentication"
};
var EXPIRY_MINUTES = {
  [AuthEmailAction.Signup]: 60 * 24,
  [AuthEmailAction.Recovery]: 60,
  [AuthEmailAction.MagicLink]: 60,
  [AuthEmailAction.Invite]: 60 * 24 * 7,
  [AuthEmailAction.EmailChange]: 60 * 24,
  [AuthEmailAction.EmailChangeNew]: 60 * 24
};
function displayNameFrom(metadata) {
  if (metadata === null || metadata === void 0) return void 0;
  for (const key of ["name", "full_name", "first_name", "display_name"]) {
    const value = metadata[key];
    if (typeof value === "string" && value.trim() !== "") return value.trim();
  }
  return void 0;
}

// packages/email/src/formatting.ts
var ZERO_DECIMAL_CURRENCIES = /* @__PURE__ */ new Set([
  "bif",
  "clp",
  "djf",
  "gnf",
  "jpy",
  "kmf",
  "krw",
  "mga",
  "pyg",
  "rwf",
  "ugx",
  "vnd",
  "vuv",
  "xaf",
  "xof",
  "xpf"
]);
var THREE_DECIMAL_CURRENCIES = /* @__PURE__ */ new Set(["bhd", "jod", "kwd", "omr", "tnd"]);
function fromMinorUnits(amountMinor, currency) {
  const code = currency.toLowerCase();
  if (ZERO_DECIMAL_CURRENCIES.has(code)) return amountMinor;
  if (THREE_DECIMAL_CURRENCIES.has(code)) return amountMinor / 1e3;
  return amountMinor / 100;
}
function formatMoney(amountMinor, currency, options) {
  if (amountMinor === null || amountMinor === void 0 || !Number.isFinite(amountMinor)) return void 0;
  const trimmed = (currency ?? "").trim();
  const code = (trimmed === "" ? "USD" : trimmed).toUpperCase();
  try {
    const formatted = new Intl.NumberFormat(options?.locale ?? "en-US", {
      style: "currency",
      currency: code
    }).format(fromMinorUnits(amountMinor, code));
    return formatted.replace(/ /g, " ");
  } catch {
    return `${fromMinorUnits(amountMinor, code)} ${code}`;
  }
}
function formatDate(unixSeconds, options) {
  if (unixSeconds === null || unixSeconds === void 0 || !Number.isFinite(unixSeconds)) return void 0;
  return new Intl.DateTimeFormat(options?.locale ?? "en-US", {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: options?.timeZone ?? "UTC"
  }).format(new Date(unixSeconds * 1e3));
}
function daysBetween(fromUnixSeconds, toUnixSeconds) {
  const seconds = toUnixSeconds - fromUnixSeconds;
  return Math.max(0, Math.ceil(seconds / 86400));
}

// packages/email/src/integrations/stripeBilling.ts
var BillingEvent = {
  SubscriptionCreated: "customer.subscription.created",
  SubscriptionUpdated: "customer.subscription.updated",
  SubscriptionDeleted: "customer.subscription.deleted",
  TrialWillEnd: "customer.subscription.trial_will_end",
  InvoicePaid: "invoice.payment_succeeded",
  InvoiceFailed: "invoice.payment_failed"
};
var BILLING_EVENT_TYPES = Object.values(BillingEvent);
var LAPSED_STATUSES = /* @__PURE__ */ new Set(["past_due", "canceled", "unpaid", "incomplete_expired"]);
function planNameFrom(subscription, fallback) {
  return subscription.items?.data?.[0]?.price?.nickname?.trim() ?? fallback;
}
function priceFrom(subscription, options) {
  const price = subscription.items?.data?.[0]?.price;
  return {
    amountFormatted: formatMoney(price?.unit_amount, price?.currency, options),
    interval: price?.recurring?.interval ?? void 0
  };
}
function userIdFromSubscription(subscription) {
  const value = subscription.metadata?.user_id;
  return value !== void 0 && value !== "" ? value : void 0;
}
function mapBillingEmail(event, context) {
  const fallbackPlan = context.defaultPlanName ?? "Pro";
  const formatting = { locale: context.locale, timeZone: context.timeZone };
  const { name } = context;
  switch (event.type) {
    case BillingEvent.SubscriptionCreated: {
      const subscription = event.data.object;
      const { amountFormatted, interval } = priceFrom(subscription, formatting);
      if (subscription.status === "trialing") return null;
      return {
        template: "subscription-created",
        dedupeKey: `created:${subscription.id}`,
        props: {
          name,
          planName: planNameFrom(subscription, fallbackPlan),
          amountFormatted,
          interval,
          renewsOn: formatDate(subscription.current_period_end, formatting)
        }
      };
    }
    case BillingEvent.SubscriptionDeleted: {
      const subscription = event.data.object;
      return {
        template: "subscription-cancelled",
        dedupeKey: `cancelled:${subscription.id}`,
        props: {
          name,
          planName: planNameFrom(subscription, fallbackPlan),
          // Only claim retained access when the period genuinely hasn't elapsed yet.
          accessUntil: subscription.current_period_end !== null && subscription.current_period_end !== void 0 && subscription.current_period_end > context.nowUnixSeconds ? formatDate(subscription.current_period_end, formatting) : void 0
        }
      };
    }
    case BillingEvent.TrialWillEnd: {
      const subscription = event.data.object;
      const trialEnd = subscription.trial_end;
      if (trialEnd === null || trialEnd === void 0) return null;
      return {
        template: "trial-ending",
        dedupeKey: `trial-ending:${subscription.id}:${trialEnd}`,
        props: {
          name,
          planName: planNameFrom(subscription, fallbackPlan),
          daysRemaining: daysBetween(context.nowUnixSeconds, trialEnd),
          // Non-null: `formatDate` only returns undefined for a non-finite input, already excluded.
          trialEndsOn: formatDate(trialEnd, formatting) ?? ""
        }
      };
    }
    case BillingEvent.SubscriptionUpdated: {
      const subscription = event.data.object;
      const previousStatus = event.data.previous_attributes?.status;
      const leftTrial = previousStatus === "trialing";
      const nowLapsed = LAPSED_STATUSES.has(subscription.status ?? "");
      if (!leftTrial || !nowLapsed) return null;
      return {
        template: "trial-expired",
        dedupeKey: `trial-expired:${subscription.id}`,
        props: { name, planName: planNameFrom(subscription, fallbackPlan) }
      };
    }
    case BillingEvent.InvoicePaid: {
      const invoice = event.data.object;
      const amountFormatted = formatMoney(invoice.amount_paid, invoice.currency, formatting);
      if (amountFormatted === void 0 || (invoice.amount_paid ?? 0) <= 0) return null;
      return {
        template: "billing-success",
        dedupeKey: `paid:${invoice.id ?? "unknown"}`,
        props: {
          name,
          planName: invoice.lines?.data?.[0]?.price?.nickname?.trim() ?? fallbackPlan,
          amountFormatted,
          invoiceNumber: invoice.number ?? void 0,
          invoiceUrl: invoice.hosted_invoice_url ?? void 0,
          periodEnd: formatDate(invoice.period_end, formatting)
        }
      };
    }
    case BillingEvent.InvoiceFailed: {
      const invoice = event.data.object;
      return {
        template: "payment-failed",
        dedupeKey: `failed:${invoice.id ?? "unknown"}:${invoice.next_payment_attempt ?? 0}`,
        props: {
          name,
          amountFormatted: formatMoney(invoice.amount_due, invoice.currency, formatting),
          reason: invoice.last_finalization_error?.message ?? void 0,
          nextAttemptOn: formatDate(invoice.next_payment_attempt, formatting),
          gracePeriodDays: context.gracePeriodDays
        }
      };
    }
    default:
      return null;
  }
}

// supabase/functions/_shared/mailer.ts
var cached = null;
function getEmailService() {
  if (cached !== null) return cached;
  const { config, warnings } = loadEmailConfig((key) => Deno.env.get(key));
  cached = createEmailService({ config, warnings });
  return cached;
}
async function sendLogged(admin, input) {
  const mailer = getEmailService();
  const options = {
    userId: input.userId,
    dedupeKey: input.dedupeKey,
    preferencesUrl: input.preferencesUrl
  };
  const idempotencyKey = mailer.buildIdempotencyKey(input.template, input.to, options);
  const subject = mailer.subjectFor(input.template, input.props, options);
  const { error: claimError } = await admin.from("email_log").insert({
    user_id: input.userId ?? null,
    to_email: input.to,
    template: input.template,
    subject,
    status: "queued",
    idempotency_key: idempotencyKey,
    metadata: input.metadata ?? {}
  });
  if (claimError !== null) {
    if (claimError.code === "23505") {
      console.info(`[email] deduped ${input.template} for ${input.to}`);
      return { status: "deduped" };
    }
    console.error(`[email] could not claim ${input.template}: ${claimError.message}`);
    return { status: "failed", code: "EMAIL_LOG_CLAIM", message: claimError.message };
  }
  try {
    const result = await mailer.send(input.template, input.to, input.props, options);
    await admin.from("email_log").update({
      status: result.skipped ? "skipped" : "sent",
      provider: result.provider,
      provider_message_id: result.id
    }).eq("idempotency_key", idempotencyKey);
    return result.skipped ? { status: "skipped" } : { status: "sent", id: result.id };
  } catch (error) {
    const described = describeEmailError(error);
    await admin.from("email_log").update({ status: "failed", error_code: described.code, error_message: described.message }).eq("idempotency_key", idempotencyKey);
    console.error(`[email] ${input.template} to ${input.to} failed: ${described.code} ${described.message}`);
    return { status: "failed", ...described };
  }
}
async function preferencesUrlFor(admin, userId, appUrl) {
  const { data, error } = await admin.rpc("email_unsubscribe_token", { uid: userId });
  if (error !== null || data === null || data === void 0) return void 0;
  return `${appUrl.replace(/\/+$/, "")}/settings?prefs=${encodeURIComponent(String(data))}`;
}

// supabase/functions/stripe-webhook/handler.ts
var stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient()
});
var cryptoProvider = Stripe.createSubtleCryptoProvider();
var SUBSCRIPTION_EVENTS = /* @__PURE__ */ new Set([
  "customer.subscription.created",
  "customer.subscription.updated",
  "customer.subscription.deleted"
]);
var HANDLED_EVENTS = /* @__PURE__ */ new Set([...SUBSCRIPTION_EVENTS, ...BILLING_EVENT_TYPES]);
function json(body2, status = 200) {
  return new Response(JSON.stringify(body2), { status, headers: { "content-type": "application/json" } });
}
async function upsertSubscription(admin, event, subscription, userId) {
  const isActive = event.type !== "customer.subscription.deleted" && (subscription.status === "active" || subscription.status === "trialing");
  const { error } = await admin.from("subscriptions").upsert(
    {
      user_id: userId,
      tier: isActive ? "pro" : "free",
      status: subscription.status,
      stripe_customer_id: typeof subscription.customer === "string" ? subscription.customer : subscription.customer.id,
      stripe_subscription_id: subscription.id,
      current_period_end: subscription.current_period_end ? new Date(subscription.current_period_end * 1e3).toISOString() : null,
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    },
    { onConflict: "user_id" }
  );
  return error === null ? null : error.message;
}
async function resolveUserId(event) {
  if (SUBSCRIPTION_EVENTS.has(event.type) || event.type === "customer.subscription.trial_will_end") {
    const subscription = event.data.object;
    return { userId: userIdFromSubscription(subscription), subscription };
  }
  const invoice = event.data.object;
  const subscriptionRef = invoice.subscription;
  const subscriptionId = typeof subscriptionRef === "string" ? subscriptionRef : subscriptionRef?.id;
  if (subscriptionId === void 0 || subscriptionId === null) return {};
  try {
    const subscription = await stripe.subscriptions.retrieve(subscriptionId);
    return { userId: userIdFromSubscription(subscription), subscription };
  } catch (err) {
    console.error(`[stripe-webhook] could not retrieve subscription ${subscriptionId}: ${String(err)}`);
    return {};
  }
}
async function resolveRecipient(admin, userId) {
  const { data, error } = await admin.auth.admin.getUserById(userId);
  if (error !== null || data?.user === null || data?.user === void 0) {
    console.error(`[stripe-webhook] could not load user ${userId}: ${error?.message ?? "not found"}`);
    return {};
  }
  return {
    email: data.user.email ?? void 0,
    name: displayNameFrom(data.user.user_metadata)
  };
}
Deno.serve(async (req) => {
  if (req.method !== "POST") return new Response("Method not allowed.", { status: 405 });
  const signature = req.headers.get("stripe-signature");
  const secret = Deno.env.get("STRIPE_WEBHOOK_SECRET");
  if (!signature || !secret) return new Response("Missing signature or webhook secret.", { status: 400 });
  const body2 = await req.text();
  let event;
  try {
    event = await stripe.webhooks.constructEventAsync(body2, signature, secret, void 0, cryptoProvider);
  } catch (err) {
    return new Response(`Webhook signature verification failed: ${String(err)}`, { status: 400 });
  }
  if (!HANDLED_EVENTS.has(event.type)) {
    return json({ received: true, ignored: event.type });
  }
  const { userId, subscription } = await resolveUserId(event);
  if (userId === void 0) {
    return json({ received: true, warning: "no user_id in subscription metadata" });
  }
  const admin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false } }
  );
  if (SUBSCRIPTION_EVENTS.has(event.type) && subscription !== void 0) {
    const dbError = await upsertSubscription(admin, event, subscription, userId);
    if (dbError !== null) return new Response(`Database error: ${dbError}`, { status: 500 });
  }
  const { email, name } = await resolveRecipient(admin, userId);
  if (email === void 0) {
    return json({ received: true, warning: "user has no email address" });
  }
  const mapped = mapBillingEmail(event, {
    nowUnixSeconds: Math.floor(Date.now() / 1e3),
    name,
    defaultPlanName: Deno.env.get("BILLING_PLAN_NAME") ?? "Pro",
    gracePeriodDays: Number(Deno.env.get("BILLING_GRACE_PERIOD_DAYS") ?? "7"),
    locale: Deno.env.get("EMAIL_LOCALE") ?? void 0
  });
  if (mapped === null) {
    return json({ received: true, emailed: false, reason: "no email for this event" });
  }
  const appUrl = (Deno.env.get("APP_URL") ?? "").replace(/\/+$/, "");
  const outcome = await sendLogged(admin, {
    template: mapped.template,
    to: email,
    props: mapped.props,
    userId,
    // Keyed to the Stripe object, so a webhook redelivery cannot produce a second email.
    dedupeKey: mapped.dedupeKey,
    preferencesUrl: await preferencesUrlFor(admin, userId, appUrl),
    metadata: { source: "stripe-webhook", stripe_event_id: event.id, stripe_event_type: event.type }
  });
  return json({ received: true, emailed: outcome.status, template: mapped.template });
});
